### ISSUE TITLE
Rebrand to BCH

### ISSUE THREAD

**Issue by cpacia** [gcash/bchd#1]
We need to go package by package and change all references to btc to bch and all references to bitcoin to bitcoin cash.

**Comment by cpacia** [comment]
Done. Keep on the lookout for anything that was missed.

**Comment by shade** [comment]
Well, there is btcjson, are you planning on converting that to bchjson? @cpacia

**Comment by cpacia** [comment]
@shade maybe. I'd like to remove the jsonrpc interface entirely in favor of grpc, but if people are using it maybe it could stay. Or maybe it could be stripped out and made into a separate package.
