### ISSUE TITLE
Many wire package limits are static and incorrect if EBS ever changes from 32MB

### ISSUE THREAD

**Issue by emergent-reasons** [gcash/bchd#110]
Discovered in #102.

At least the following constants should actually be dynamic or initialized based on EBS.

- `MaxMessagePayload`
- `maxCountSetCancel`
- `maxAlertSize`
- `maxCountSetSubVer`
- `MaxBlockPayload`
- `maxTxPerBlock`
- `maxFlagsPerMerkleBlock`
- `maxTxInPerMessage`
- `maxTxOutPerMessage`

**Comment by cpacia** [comment]
`maxAlertSize` I think we want to get rid of the alert message as it's not used in bitcoin cash

**Comment by emergent-reasons** [comment]
Ok if you don't mind I'll do that in the PR that will cover this and #102.

**Comment by zquestz** [comment]
NOTE: the `addblock` utility also needs the EBS values. Just wanted to include that here.

**Comment by emergent-reasons** [comment]
@zquestz as I think you mentioned in that issue, to be totally consistent I think we would need to request EBS from the running server at runtime because the command line arguments for the server would not be available to the cli. For now, I am trying at least to make the server and CLI to have the same defaults and read from the same config file.

**Comment by cpacia** [comment]
This is complete right @emergent-reasons ?

**Comment by zquestz** [comment]
@emergent-reasons ping, this was done right?

**Comment by emergent-reasons** [comment]
Sorry i just saw this ping.

Any cli code will use its own default unfortunately so if bchd is run with
an arg to change ebs, the cli will not pick it up.

But anything using wire package should get the right default and all
dependent values should be correct.

There is a lot of duplication in configs though so I need to check what
addblock is using. Will do when I get home.

**Comment by zquestz** [comment]
I think the other binaries can be covered in a new issue. I think what was described here was resolved. =)

**Comment by emergent-reasons** [comment]
Oh yes. This is actually closed by #132. Not sure why it is open. Yes, other binaries need a little more attention.
