### ISSUE TITLE
Convert all addresses in tests from legacy to cashaddress format

### ISSUE THREAD

**Issue by cpacia** [gcash/bchd#14]
Many tests have address strings in them that are decoded for the purpose of the test. The tests may still pass with the legacy address but to make sure the codebase is as true to BCH as possible they should all be converted to cashaddresses. 

This needs to be done after the cashaddress is implemented in `bchutil`.

**Comment by zquestz** [comment]
I am interested in tackling this. If anyone else jumps on it please ping me. =)

**Comment by cpacia** [comment]
I have already have updated some of them but I'm not sure if I got all of them. I'm not actually sure where there are either as you can't easily search for bitcoin addresses.

**Comment by zquestz** [comment]
I will hunt around. =)

**Comment by zquestz** [comment]
You got almost all of them. I found 3 more. Fixed in PR https://github.com/gcash/bchd/pull/32
