### ISSUE TITLE
MaxSigOps limit is incorrect

### ISSUE THREAD

**Issue by cpacia** [gcash/bchd#178]
We're currently doing `20000 * excessiveBlockSize` but the way it's implemented in ABC is `20000 * sizeOfBlock` where `sizeOfBlock` is rounded up to the nearest 1 MB.

**Comment by emergent-reasons** [comment]
I found it. Please disregard.

**Comment by zquestz** [comment]
Progress?

**Comment by cpacia** [comment]
done
