### ISSUE TITLE
Max peers reached 125 - but real peers less than 125

### ISSUE THREAD

**Issue by nshopik** [gcash/bchd#183]
Logs complains `Max peers reached [125]` but netstat show there less than 20 peers established TCP sessions

**Comment by cpacia** [comment]
Are you counting both inbound and outbound in the 20?

**Comment by nshopik** [comment]
yeah both

**Comment by nshopik** [comment]
I think that issue even prevent node receiving new blocks at some point, i just restarted node and its started adding orphan blocks

**Comment by cpacia** [comment]
what version are you running?

**Comment by nshopik** [comment]
0.14

**Comment by zquestz** [comment]
So I am having a hard time replicating this issue. I see my node connecting to more than 25 peers, are you still seeing this behavior? I will look a little closer at the code again tonight, but my node is definitely able to connect to more than 25 peers. =\

**Comment by nshopik** [comment]
My node HDD was failed, so i need rebuild it and try to reproduce it once again. I'll report back

**Comment by nshopik** [comment]
Closing for now, I'll repopen if able to reproduce issue after rebuild
