### ISSUE TITLE
Cannot connect to BU nodes

### ISSUE THREAD

**Issue by imaginaryusername** [gcash/bchd#184]
bchd on Avalanche branch seems to connect to ABC and XT nodes just fine, but cannot connect to BU peers even via addnode. No relevant output has been observed on outbound, but inbound seems to display similar message as #155  

I tried with my own BU 1.5.1 nodes, but it seems to be unable to connect to 1.4.0 I found on my other nodes' peerlist as well.

**Comment by cpacia** [comment]
We could just ignore it though I'm not sure we want to just drop unknown messages as it could be a ddos vector. 

Alternatively we could actually implement the message and the correct handling for it. 

It would be better, however, if they made sure they were only sending it to compatible nodes.

**Comment by zquestz** [comment]
Yeah this seems like BU should not send unsupported messages to other clients. However, I do think a PR to add support for this message also makes sense. Also, is this only happening on the Avalanche branch or are we not connecting to any BU nodes right now?

**Comment by imaginaryusername** [comment]
Can confirm, I'm on the normal branch of bchd, tried connecting to my own BU1.5.1 node and still got `Can't read message from 198.50.179.86:8333 (outbound): ReadMessage: unhandled command [xversion]`.

**Comment by zquestz** [comment]
We can add a no-op for `xversion` messages for now. Want to submit a PR? =)

**Comment by zquestz** [comment]
Actually I have a stub for the xversion message that should fix this issue. Will be putting up a PR tonight hopefully.

**Comment by zquestz** [comment]
This is now fixed in master. =)

**Comment by imaginaryusername** [comment]
Just chiming in to say addnodes to BU1.5.1 peers now works well!
