### ISSUE TITLE
IBD hangs at block 281736

### ISSUE THREAD

**Issue by checksum0** [gcash/bchd#187]
Master HEAD hangs at block 281736 indefinitely (24h+). This happened thrice, twice on the same VM  on a dedicated server of mine and once on a different VM from a well known VPS provider.

Always launch with --prune.

EDIT: Restarting the client will go over that block and no other blocks seems to cause an issue.

![image](https://user-images.githubusercontent.com/26656348/53068583-00da4c80-34a7-11e9-9777-4adaae9c83c6.png)

**Comment by zquestz** [comment]
Going to try this now.

**Comment by checksum0** [comment]
Let me know if you'd like to have other information.

**Comment by checksum0** [comment]
I was able to reproduce with debuglevel=debug, however it doesn't give any more information. It just decide to hang out there somewhere on on 21-01-2014, no error, nothing obvious.

Also, ctrl+c will never lead to the client gracefully exiting, it just hangs out there again.

Attached log file.

[log.txt](https://github.com/gcash/bchd/files/2883461/log.txt)

**Comment by zquestz** [comment]
I had no issues getting past that block...

![screenshot from 2019-02-19 23-25-41](https://user-images.githubusercontent.com/83898/53073734-b6080700-349d-11e9-9145-e13f6e7bbe92.png)

**Comment by checksum0** [comment]
I'll try that tomorrow with some addnode.

**Comment by checksum0** [comment]
Cannot reproduce anymore so I'll close this for now.
