### ISSUE TITLE
Implement fast sync mode

### ISSUE THREAD

**Issue by cpacia** [gcash/bchd#19]
Fast sync has always been possible but nobody has bothered implement it. There are a number of different ways to do so and it seems people are holding out for an "ideal' solution. 

While #17  will likely improve the initial block download speed, we should be able to better. 

The easiest way to implement fast sync is to just extend the `checkpoint` object to include the hash of the UTXO set and a data source. 

Then we can just put the UTXO set at that checkpoint up on AWS or IPFS and have the node download the UTXO set at start up, parse it, validate the hash against the checkpoint and save to the database. 

People will complain about the security model of this but in reality it's not much different than syncing from genesis. In both cases your options are:

Syncing from genesis: trust the developers hardcoded the correct genesis block or compile the software from source and verify the genesis block against a known good source.

Fast sync from checkpoint: trust the developers hardcoded the correct checkpoint and UTXO hash or compile the software from source and verify the checkpoint and UTXO hash against a known good source.

Not that much different.

This is far from the ideal way of doing it, but IMO it's better to have something than nothing. Especially with IBD taking longer. 

The first hurdle here is to figure out how to hash the UTXO set. Ideally we would use the same ECMH algorithm that is being developed by Thomas van der Wassen for ABC, but we'll need to port that over which isn't that easy. Or maybe we could use cgo. 

If we must we could hash it some easier way for now and change the algorithm later. Since nothing is committed we can change the algorithm by just making a new release. 

This also requires a utility cmd to calculate the hash of the UTXO at a given block so that we can build the checkpoint and others can verify it.

**Comment by homakov** [comment]
>People will complain about the security model of this but in reality it's not much different than syncing from genesis. In both cases your options are:



Not just "different" but exactly the same. I talked about this problem here:

https://medium.com/fairlayer/snapshots-the-simplest-way-to-increase-number-of-full-nodes-3ebf2aaef515

Make sure chainstate is deterministic, because now it's not.
