### ISSUE TITLE
Switch to gRPC API

### ISSUE THREAD

**Issue by cpacia** [gcash/bchd#20]
gRPC provides a much nicer interface than the JSON RPC and websocket APIs. There is a WIP PR in btcd to add gRPC support https://github.com/btcsuite/btcd/pull/1075.

We could build on that and get it to where it needs to be to merge in here. Once that's in I would prefer to remove all JSON RPC API altogether and get rid of the `btcjson` package. 

gRPC has a nice feature in that there is a plugin that lets you spawn a REST reverse proxy to the API for people who absolutely need a REST JSON interface. 

In the course of doing so we should make sure we add all the RPCs needed to use bchd as a backend SPV wallet server. This would imply a creating a `getheaders` endpoint which accepts a block locator just like the wire message does. Plus a streaming headers endpoint for wallets to subscribe to. 

Finally we'll need to serve SPV proofs either from a separate API or with the transactions response.

**Comment by swdee** [comment]
For reference SPV proof ability is available with RPC commands gettxoutproof and verifytxoutproof implemented in this PR https://github.com/gcash/bchd/pull/153
