### ISSUE TITLE
Add "invalidateblock" RPC capability

### ISSUE THREAD

**Issue by Mengerian** [gcash/bchd#202]
When trying to test out BCHD on the Upgrade Testnet for the May 15th upgrade, I ran into the issue that I can't tell BCHD to invalidate a block.

Since the Upgrade Testnet has less PoW than the regular testnet, it uses "invalidateblock" to ensure clients follow the correct chain.

Having this RPC capability in BCHD would be nice :)

"getchaintips" would also be nice, but lower priority.

Upgrade Testnet info here: https://github.com/bitcoincashorg/bitcoincash.org/blob/master/workgroups/wg-testing/2019-05-15_upgrade_testnet.md

**Comment by cpacia** [comment]
You can also use `--connect=` to make it only connect to specific nodes. This is how I tested syncing to the upgrade testnet.
