### ISSUE TITLE
Script Engine doesn't make use of hashcache

### ISSUE THREAD

**Issue by cpacia** [gcash/bchd#203]
The engine has a hashcache field but it is unused. Also the code to build and make use of the hashcache is commented out in the blockchain package. Presumably this slipped through the cracks since the cache was only used on segwit transactions in btcd.

TODO:

- [ ] Go through all the checksig opcodes and make use of cache if `vm.hashcache != nil`
- [ ] Uncomment/create code in the blockchain package to build the cache and pass it into the vm. 
- [ ] Take a look at the mempool package as well as a hashcache can probably be created there as well.

**Comment by zquestz** [comment]
Can you provide a bit more context on the benefits and purpose of that cache?

**Comment by cpacia** [comment]
Oh, the sig hashes can be cached so they are recalcualted every time an input is validated. Should result in a validation speed up.
