### ISSUE TITLE
Syncing stuck every time at block 577668

### ISSUE THREAD

**Issue by masaruduy** [gcash/bchd#221]
Can't sync above block 577668. Every time I start from the beginning, we are getting errors at that block such as: 

Rejected block 0000000000000000024578c467057df411eb72822dac836772164a27bed46a5b from 35.198.162.222:8333 (outbound): previous block 0000000000000000001df2299a0d705bc95df7045398a32d1dea5ccff7bb9fb6 is known to be invalid

**Comment by cpacia** [comment]
Was this a fast sync node and did you have any hard shutdowns?

**Comment by masaruduy** [comment]
hard sync yes
but no hard shut down

**Comment by cpacia** [comment]
Oh wait a second. I think that block was the bug we had in 0.14.0. I would recommend upgrading to 0.14.2. And if you fast synced it I would just delete the data directory and fast sync again. It would likely be quicker than fixing the db.

**Comment by masaruduy** [comment]
how do you upgrade? I can't find that in the docs
thanks

**Comment by postables** [comment]
@masaruduy you just need to download the binaries from the releases page and use the latest one. Alternatively you can do `go get -u github.com/gcash/bchd` and build from source

**Comment by masaruduy** [comment]
Ok thanks!
