### ISSUE TITLE
Suggestion: Use counterfeiter to generate mocks for testing the gRPC API

### ISSUE THREAD

**Issue by postables** [gcash/bchd#224]
Love the gRPC API so far! I'm currently working on integrating it within a payment system for one of my projects. Recently I've been using [counterfeiter](https://github.com/maxbrunsfeld/counterfeiter) to generate mocks for interfaces to enable easier testing.

Counterfeiter supports using `go generate` to generate mocks like [so](https://github.com/maxbrunsfeld/counterfeiter#step-2---add-gogenerate-directives).

Alternatively, I do something similar to the following to generate mocks for third party interfaces:

```make
# Rebuild generate code
COUNTERFEITER=go run github.com/maxbrunsfeld/counterfeiter/v6
.PHONY: gen
gen:
	@echo "===================    regenerating code    ==================="
	$(COUNTERFEITER) -o ./mocks/bch.mock.go \
		github.com/gcash/bchd/bchrpc/pb.BchrpcClient
	@echo "===================          done           ==================="
```

I'd be happy to open up a PR to do this as it seems like it's something that would be very useful for other people building ontop of the gRPC API

**Comment by cpacia** [comment]
Thanks. We'd love to have more tests for the API.

**Comment by postables** [comment]
sounds good! let me open up a PR :)
