### ISSUE TITLE
Update script tests to pass all ABC test vectors

### ISSUE THREAD

**Issue by cpacia** [gcash/bchd#254]
The ABC test vectors can be found here https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/src/test/data/script_tests.json

Basically we want to take the entire file and copy it into bchd and run these tests. 

We have something similar in `txscript/reference_test.go` which runs `txscript/data/script_tests.json` however it doesn't contain all the test cases. Some small refactoring will be needed to make sure all the errors in the ABC test vectors translate to errors in bchd.

**Comment by zquestz** [comment]
https://github.com/gcash/bchd/pull/253
