### ISSUE TITLE
Improve CI testing

### ISSUE THREAD

**Issue by cpacia** [gcash/bchd#256]
So I think we need to beef up the CI testing on this repo. 

Ideally we would have the following:
- ABC node running on mainnet
- ABC node running on testnet
- BCHD node running on mainnet
- BCHD node running on testnet

Frequent polling of these nodes to compare the best hash and height. If there is a difference, it should send out notifications. Possibly a slack notification which would get pushed to our phones. 

In addition:
It should probably do an IBD on both mainnet and testnet at least once per week (using master branch). I think ABC does it every day, but that might be slightly overkill. 

IBD should download the blockchain from an ABC node. 

It should also use the `--nocheckpoints` so that it validates the scripts from genesis. 

Finally:
It should do an IBD using `--fastsync` and as well as full indexes probably less frequently than the normal IBD.

**Comment by zquestz** [comment]
We now have a node on both testnet and mainnet.

Mainnet - bchd.greyh.at
Testnet - bchd-testnet.greyh.at

**Comment by haplo** [comment]
I'd like to help with this (or other open tasks you may have).

These IBD tests are to be set up in the project's TravisCI instance, right?

From what @zquestz says we are missing a testnet ABC node. Also are those nodes being used for anything else? Will they be available while they are undergoing IBD?

I will set up a testnet node on my server and start scripting the IBD. I will try to capture at least timing information, memory and network usage would also be nice.

**Comment by jasonbcox** [comment]
Glad to see you working on this.  Some reasons why we run IBD daily:
* Our release cadence is currently every 2 weeks.  Running IBD weekly would allow us a 1-week timeframe at best to fix issues.
* Commit cadence has increased, especially in regards to backports, meaning potentially more changes to consensus-related codepaths.
* Ideally, we'd catch issues as soon as possible so that bisecting the bad commit takes significantly less time.

Just some thoughts to keep in mind. :)

**Comment by cpacia** [comment]
Thanks @jasonbcox. Unfortunately we're not on that fast of a release cycle so doing it less frequently is probably ok for now.

**Comment by cpacia** [comment]
@haplo that would be awesome. We have some funds available to pay for servers. We've had some discussion about doing AWS instances that we only pay for while they are running the IBD so as to minimize cost.

**Comment by zquestz** [comment]
This is stale and we have added regtest cluster testing, plus are working with BU on syncing improvements. Closing.
