### ISSUE TITLE
gRPC methods needed

### ISSUE THREAD

**Issue by jcramer** [gcash/bchd#259]
I am working on getting gRPC wired up to SLPDB as nearly a drop-in replacement for RPC.  Here are the gRPC methods we would need without requiring big code changes or breaking legacy RPC support in order of call frequency (relative impact on performance):

1. `getAddressUnspentOutput()` should have an option to account for the mempool transactions

2. `getUnspentOutput(hash: string, index: number, includemempool: boolean) -> UnspentOutputResponse` (similar to RPC `getTxOut()`)

3. `getRawMempool() -> GetRawMempoolResponse` (similar to RPC `getRawMempool()`)

4. `subscribeRawTransactions() -> ClientReadableStream<RawTransactionNotification>`

5. `subscribeRawBlock() -> ClientReadableStream<RawBlockNotification>`

**Comment by jcramer** [comment]
I updated the list above to include new "include mempool" option in the `getAddressUnspentOutput()` rpc method.

**Comment by cpacia** [comment]
@jcramer what does the ClientReadableStream refer to? Is it just the raw block? Would this PR be appropriate for what you are requesting? https://github.com/gcash/bchd/pull/263

**Comment by jcramer** [comment]
Yes, #263 takes care of item 4.

**Comment by cpacia** [comment]
Just waiting on the last two.

**Comment by jcramer** [comment]
One more item that would really speed things up for SLPDB would be having a "spentToTxid" field on the return of a transaction object. 

In SLPDB we have to crawl the token graph forwards through time, that means for each outpoint we need to check if it has been spent (easy with RPC getTxOut command).  If it is spent we then need to lookup which txid it was spent in using a fully indexed mongodb (bitdb).  So in SLPDB that is two fairly slow queries (for every outpoint!).

If BCHD had the "spentToTxid" field accessible getTransaction gRPC it would result in a _very nice_ speed up the dagging process for SLPDB.

**Comment by jcramer** [comment]
Please add mediantime to blockinfo

**Comment by zquestz** [comment]
This has just been added. =)

**Comment by jcramer** [comment]
@zquestz When I call `getMedianTime()` from gRPC getBlockInfo() it always returns 0 regardless of the block height.  I call getTimestamp() and it works as expected.  I have updated and recompiled the protoc files, so I'm not sure if I'm missing something or...

**Comment by cpacia** [comment]
which rpc are you using to get the blockinfo?

**Comment by jcramer** [comment]
It works now, i was using Josh's node and it was updated yet.

**Comment by zquestz** [comment]
I believe this is now complete! =)

**Comment by cpacia** [comment]
done
