### ISSUE TITLE
Following reorg, downstream nodes fail to receive blocks from bchd

### ISSUE THREAD

**Issue by discoltk** [gcash/bchd#262]
Previously there was a bug which caused bchd to crash or hang on reorg.    At the time, I noticed that even after restarting bchd my downstream nodes failed to receive blocks.   Without putting much thought into it, I restarted the downstream nodes and resolved the problems.   Because this was obviously a bug on bchd side I assumed the hang was the reason.    

Following patches released which fixed the prior issue with hanging on reorg, I have now experienced the same behavior I'd observed previously with the downstream node, despite the fact that BU did not hang or crash.

    2019-06-23 18:47:39.376 [INF] CHAN: REORGANIZE: Chain forks at 0000000000000000018dfbc3f4ab861c00d59a3bfd2d9d80b216abb8a1be890b (height 588214)
    2019-06-23 18:47:39.376 [INF] CHAN: REORGANIZE: Old best chain head was 000000000000000001ace7ba1ca09b725090aaa53daada0af36df0c87239adef (height 588215)
    2019-06-23 18:47:39.376 [INF] CHAN: REORGANIZE: New best chain head is 000000000000000000144e17b0cf574f10e1f77fa42bde1794465655547ac02e (height 588216)

The above rorg occured on June 23rd.    Following this, one error was shown for each downstream node with the following message:

    2019-06-23 18:49:34.858 [WRN] PEER: Received reject message from peer <redacted> (inbound), code: REJECT_NONSTANDARD, reason: non-final

Both downstream nodes (running BUCash:1.6.0) remained connected to bchd, however they did not receive further blocks after the reorg event.    Restarting the BU nodes did allow them to sync back to the current chain tip.   Other BU nodes of the same version which were upstream handled the reorg without issue.

**Comment by zquestz** [comment]
Thank you for your detailed report. I am looking into this now.

**Comment by zquestz** [comment]
I think I know what is happening!

If you look at the `handleBlockchainNotification` method at `manager.go:1477` it only passes along the block inventory when the block is accepted. In the case of a reorg, that block would not be accepted, and it would only run the connected handler which does not pass along the block inventory. Therefore downstream nodes would not get announced the freshly reorged blocks. I assume in your setup the nodes are only connected to bchd?

Anyhow, the fix shouldn't be too bad. I am working on it now. =)

**Comment by zquestz** [comment]
Fix has been merged. Going to close this. Let us know if you still experience issues!
