### ISSUE TITLE
gRPC endpoint "getUnspentOutput" returns spent items

### ISSUE THREAD

**Issue by jcramer** [gcash/bchd#280]
Running from latest master 2e2e205 and node is synced 100%, `getUnspentOutput` returns spent TXOs sometimes until node is restarted.  In SLPDB we rely heavily on this method only returning unspent results.  

- I toggled the "includeMemoryPool" flag and that has no impact.

- Restarting BCHD resolves the problem.  So it seems that this happens to transactions spent _while_ BCHD is running.

**Comment by jcramer** [comment]
Thanks for such a fast response 💯

**Comment by jcramer** [comment]
This issue seems to be not fixed running on faa80bc.  

What's strange is that running `bchctl gettxout "txid" vout` returns no response for a spent txo, as expected.  But calling grpc `getUnspentOutput` does not return the error response as expected for grpc, instead its returning the result as if its unspent.

Again, the issue gets resolved after restarting BCHD, as this bug is impacting the spent txos after BCHD has been started.

Reproduce:
Not sure if you have any nodes running on faa80bc, but if you do you can call `getUnspentOutput` for: 
- setHash = reverse of txid "2e0510bdfb571896846121a2e4bb9ee01a76ce7c6d29d91b9b66179be2c67380"
- setIndex = 1

**Comment by jcramer** [comment]
https://github.com/gcash/bchd/pull/282#issuecomment-531225076

**Comment by zquestz** [comment]
Reopening this issue as there is still a race condition!

**Comment by jcramer** [comment]
Yes, I'm pretty sure there is, are you able to reproduce it?

**Comment by zquestz** [comment]
I am planning on digging into this tonight. Pretty sure there is a race condition. =)

**Comment by jcramer** [comment]
you are already apprised, but here is the repo that can be used to reproduce the issue:

https://github.com/jcramer/grpc-gettxout-test
