### ISSUE TITLE
rpcallowip and rpclisten are missing. what's the alternative?

### ISSUE THREAD

**Issue by krtschmr** [gcash/bchd#289]
the normal bitcore clients support `rpclisten` and `rpcallowip`. what's the replacement for bchd?

**Comment by cpacia** [comment]
Which rpc do you want to use..the json-rpc or grpc?

**Comment by zquestz** [comment]
So bchd already supports `rpclisten`

```
--rpclisten=               Add an interface/port to listen for RPC
                                 connections (default port: 8334, testnet:
                                 18334)
```

However I don't think we have an explicit whitelist.  For now you would just need to set `rpcuser` and `rpcpass` and handle access that way.

I would definitely be open to a PR adding `rpcallowip`.
