### ISSUE TITLE
BCH November 15th, 2019 Planned Network Upgrade

### ISSUE THREAD

**Issue by jeansouza** [gcash/bchd#290]
Is BCHD supporting the BCH November 15th, 2019 Planned Network Upgrade?

**Comment by cpacia** [comment]
Yeah it's already merged

**Comment by zquestz** [comment]
To be super clear, bchd 0.15.0 fully supports the Nov upgrade!

**Comment by jeansouza** [comment]
@cpacia @zquestz ok, thank you guys! :)
