### ISSUE TITLE
Unspent output hash

### ISSUE THREAD

**Issue by jeansouza** [gcash/bchd#291]
I'm starting to use your gRPC to get the unspent outputs for an address, and I'm not beeing able to decode the hash of the output. The hash property (`unspent.outpoint.hash`) is a buffer, and I tried to decode to hex but the result wasn't right.

Can somebody help me, please?

Ps: I'm using Node.js.

**Comment by cpacia** [comment]
Yup. There's a pattern that exists in both this codebase as well as the c++ codebases where when you have a hash represent as a byte array it's in little endian format. When it's a hex string it's in big endian. 

So in this case you would just reverse the bytes to get the format you're used to seeing.

**Comment by jeansouza** [comment]
@cpacia should I use the method `swap32` for that?

**Comment by jeansouza** [comment]
@cpacia nervermind, I was able to do it with a simples reverse. Thank you so much for the help! :D
