### ISSUE TITLE
performance issues

### ISSUE THREAD

**Issue by nshopik** [gcash/bchd#304]
So I noticed that performance not so great on my node like for example:

`Processed 1 block in 1m36.03s (30 transactions, height 608836 (100.00%)`

and that decent machine (Intel(R) Xeon(R) CPU E31220 @ 3.10GHz), where BU usually process such small blocks on fraction of second.

**Comment by zquestz** [comment]
This is normal. This is not the time it takes to process the block, but the time since the last block + block processing time.

For instance in my logs:

```
2019-11-13 18:37:21.912 [INF] SYNC: Processed 1 block in 9m42.19s (237 transactions, height 608898 (100.00%), 2019-11-13 18:36:46 +0000 UTC, ~12 MiB cache)
```

This doesn't mean it took 9+ minutes, it means it was 9+ minutes since the last block was processed.
