### ISSUE TITLE
Get unspents

### ISSUE THREAD

**Issue by teran-mckinney** [gcash/bchd#322]
Is there a RPC or REST call where I can get unspents by an address?

**Comment by cpacia** [comment]
Yeah there is a gRPC call:

```
rpc GetAddressUnspentOutputs(GetAddressUnspentOutputsRequest) returns (GetAddressUnspentOutputsResponse) {}
```

**Comment by teran-mckinney** [comment]
Thank you! Where is rRPC documented?

**Comment by zquestz** [comment]
There is information here: https://medium.com/@bchd.cash/announcing-the-bchd-grpc-api-16b3a833292e

You can also check the proto file `bchrpc.proto`
