### ISSUE TITLE
Fix uPnP

### ISSUE THREAD

**Issue by JettScythe** [gcash/bchd#323]
I recently had some router issues and had to go back to default settings.
Was going to be lazy and tried `./bchd --upnp` but get `[WRN] SRVR: can't add UPnP port mapping: Error 500 for AddPortMapping` in response.

Made sure the external ip wasn't listed in the config file, set `upnp=1`, ran `./bchd` & got the same error. 

Would do more tinkering myself, but not sure where to find the error codes to learn more.

**Comment by zquestz** [comment]
I will need a bit more info to debug this. I can personally use the upnp just fine and can't seem to replicate this error.

**Comment by JettScythe** [comment]
I just ended up adding the port forwarding manually. 
Running Manjaro 18.1.3 
x86_64 Linux 4.19.84
Router is a Hitron Coda 4582U Software v 2.0.10.36T6
Lmk what other info you might need. Unfortunately the logs just say `2019-11-27 12:15:03.070 [WRN] SRVR: can't add UPnP port mapping: Error 500 for AddPortMapping` whenever I tried using upnp, and I've already edited the config.

**Comment by gubatron** [comment]
how long has the router been without a reboot?
are there any other apps having issues with UPnP? 

In my experience some router's UPnP implementations can bug out after long periods of time or intense UPnP activity

**Comment by zquestz** [comment]
Very odd, I can confirm it works on my routers... Going to close this until we get more info, or somehow get a similar router for testing!
