### ISSUE TITLE
How do I create a schnorr multi-sig transaction using bchd？

### ISSUE THREAD

**Issue by minchenzz** [gcash/bchd#326]

**Comment by cpacia** [comment]
You'd need to build one manually.

Here's some example code if you're interested https://github.com/cpacia/multiwallet/blob/master/bitcoincash/wallet.go#L449

**Comment by minchenzz** [comment]
`
        pr1, _ := hex.DecodeString("f57aabd6518a9be2735fee63472c053e8d5704a4f878815199f65eaad46ca7e9")
	pr2, _ := hex.DecodeString("d37166a7b39c3ff6cb25c8753be5a1a3e6d8d71cacadfbc9fbde9e53f376f548")

	prik1, _ := bchec.PrivKeyFromBytes(bchec.S256(), pr1)
	prik2, _ := bchec.PrivKeyFromBytes(bchec.S256(), pr2)

	tx := wire.NewMsgTx(2)
	preHash, _ := chainhash.NewHashFromStr("df616ed8efb8837e4770d8551b9bb2175a650c348b8eeea92a4d6a5af6d3cc03")
	outPoint := wire.NewOutPoint(preHash, 1)
	txIn := wire.NewTxIn(outPoint, nil)
	tx.AddTxIn(txIn)
	outScript, _ := hex.DecodeString("76a914a30b70f478434448cfcc6e6ae5a6ffc6b883df6388ac")
	tx.AddTxOut(wire.NewTxOut(10000, outScript))
	redeem, _ := hex.DecodeString("5221020a043ff67e5614fd6b42bdc80b4efce3ab6c17a109e5a09bad88f776854025cb21025fb644c63ccf7d980dc931aaf8c959a2e9aa8c7f1cb2a27601457808256eff6e2102b79e1340bb8eb8d6f903c357ccb780c30fedc6dd97710fff924765409b7db8e453ae")

	sig1, _ := txscript.RawTxInECDSASignature(tx, 0, redeem, txscript.SigHashAll, prik1, 1000000)
	sig2, _ := txscript.RawTxInECDSASignature(tx, 0, redeem, txscript.SigHashAll, prik2, 1000000)
	
	sigScript := bytes.Buffer{}
	
	sigScript.Write([]byte{txscript.OP_0})
	scriptSig1, _ := txscript.NewScriptBuilder().AddData(sig1).Script()
	sigScript.Write(scriptSig1)
	scriptSig2, _ := txscript.NewScriptBuilder().AddData(sig2).Script()
	sigScript.Write(scriptSig2)
	
	rd, _ := txscript.NewScriptBuilder().AddData(redeem).Script()
	sigScript.Write(rd)
	fmt.Println(hex.EncodeToString(sigScript.Bytes()))
	txIn.SignatureScript = sigScript.Bytes()

	buf := bytes.Buffer{}
	tx.Serialize(&buf)
	fmt.Println(hex.EncodeToString(buf.Bytes()))`

Thank yor!
This is my ECDSA signature code，I can broadcast successfully.
But when I use "RawTxInSchnorrSignature" instead of "RawTxInECDSASignature". I got a "mandatory-script-verify-flag-failed (Signature cannot be 65 bytes in CHECKMULTISIG) (code 16)" error.
