### ISSUE TITLE
Auto generated self-signed certificate not working for gRPC

### ISSUE THREAD

**Issue by jcramer** [gcash/bchd#330]
I was trying to utilize the self-signed `rpc.cert` file that bchd creates in the `~/.bchd` directory.  I noticed with the grpc-bchrpc-node npm package that if I use constructor params { url: "localhost:8335", rootCertPath: "/root/.bchd/rpc.cert"} I get the following error: 

`E1231 11:16:38.386759000 4525288896 ssl_transport_security.cc:1245]    Handshake failed with fatal error SSL_ERROR_SSL: error:1414D17A:SSL routines:tls12_check_peer_sigalg:wrong curve.`

I'm not sure if I'm missing the purpose of the auto generated self-signed certificate and if there is some know reason why it doesn't work for connecting to the gRPC server from localhost.

I can get the server to work by creating a new self-signed cert:

```
openssl req -x509 -out localhost.crt -keyout localhost.key \  -newkey rsa:2048 -nodes -sha256 \
  -subj '/CN=localhost' -extensions EXT -config <( \
   printf "[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")
```

Then in `grpc-bchrpc-node` I can use:

`const grpc = new GrpcClient({ url: "localhost:8335", rootCertPath: "<path to cert>/localhost.crt" });`

**Comment by zquestz** [comment]
I have fixed the issue in bchutil -> https://github.com/gcash/bchutil/pull/20

Once that lands I can pull it into bchd and certificates will just work as they should. =)

**Comment by zquestz** [comment]
Will be resolved when https://github.com/gcash/bchd/pull/342 lands.
