### ISSUE TITLE
An error about create multisig address.

### ISSUE THREAD

**Issue by minchenzz** [gcash/bchd#331]
Sometimes 'bchutil.DecodeAddress()' will report an error
```
    a, err := bchutil.DecodeAddress("2MscXFWM3yfDTYxGGC2dXCZvcMd6ySyqgPt", &chaincfg.TestNet3Params)
    // err = checksum mismatch
```

```
    decoded, _, _:= base58.CheckDecode("2MscXFWM3yfDTYxGGC2dXCZvcMd6ySyqgPt")
    a, _:= bchutil.NewLegacyAddressScriptHashFromHash(decoded, &chaincfg.TestNet3Params)
    _, addrs, _, _:= txscript.ExtractPkScriptAddrs(append(append([]byte{txscript.OP_HASH160, txscript.OP_DATA_20}, a.ScriptAddress()...), txscript.OP_EQUAL), &chaincfg.TestNet3Params)
    address := addrs[0].EncodeAddress()
    // address pqzqwff28ghtzhy0cxxlgr0stv6v3l57zy8fpht23f
```

pubkey1 = 037dedfbef7360e7dc1eeecdb6f3c2e6764f8b6470a7b47e0230c2456e639fae9d
pubkey2 = 025ad242dcbd0cb90a5b7afc73e0fe82ff3e49bba582533b9c64e8090e915004af
pubkey3 = 028c2805557bef3f6bdaec1b03a5a3ffd14264997d2757844ea578bfc209cc8150
redeemscript = 5221037dedfbef7360e7dc1eeecdb6f3c2e6764f8b6470a7b47e0230c2456e639fae9d21025ad242dcbd0cb90a5b7afc73e0fe82ff3e49bba582533b9c64e8090e915004af21028c2805557bef3f6bdaec1b03a5a3ffd14264997d2757844ea578bfc209cc815053ae

**Comment by cpacia** [comment]
This is an intermittent error or always with that address?

**Comment by zquestz** [comment]
I can replicate this bug, I am looking into it!

**Comment by zquestz** [comment]
Just for the record, the `cash-addr` gem from Coinbase does not exhibit this behavior. Neither does `https://cashaddr.bitcoincash.org`.

https://github.com/coinbase/cash-addr

Was just double checking that other conversion tools don't have issues.

**Comment by zquestz** [comment]
I have found the issue and will be posting a PR to fix this later tonight.

**Comment by zquestz** [comment]
Once the PR linked gets merged, then I can bump bchutil in bchd to resolve the issue.
