### ISSUE TITLE
Getblocktemplate difficulty on testnet

### ISSUE THREAD

**Issue by checksum0** [gcash/bchd#338]
The difficulty on testnet drops to 1 after 20 minutes without a block found. While BCHD do accept these blocks in its consensus layer, it does not lower the difficulty in its getblocktemplate response after 20 minutes, continuing instead to look for a block at the normal difficulty.

This is important to find block regularly on testnet despite the large hashrate variations.

**Comment by cpacia** [comment]
So it looks to me like the code doesn't push a new template unless a new block comes in or the transactions have changed and a certain amount of time has passed. It does not look like it automatically pushes a new template when the 20 minute threshold passes. 

But it does look to me like the code would update the difficulty when it does push a new template (though someone else is likely to have mined the min difficulty block by that point). 

I wonder if there's a way to test this a make sure I'm indeed correct. If so it would require making the long poll return with an updated template after the 20 minute threshold expires.

**Comment by checksum0** [comment]
I ended up eventually finding a block a diff 1, I think it's just much slower to update the difficulty than compared to Satoshi's code.
