### ISSUE TITLE
Do not force coinbase flags

### ISSUE THREAD

**Issue by checksum0** [gcash/bchd#339]
Do not force coinbase flags for blocks mined with BCHD, that is uncool as we say, especially if there's no way to configure it (I see none).

![image](https://user-images.githubusercontent.com/26656348/75333034-63e98680-5853-11ea-8d3a-a9c476a98258.png)

https://github.com/gcash/bchd/blob/4efc7465345efde0f6ba4c86081e35c23e880f6b/mining/mining.go#L34

**Comment by cpacia** [comment]
merged
