### ISSUE TITLE
Question on the minimum transaction size of 100 bytes

### ISSUE THREAD

**Issue by zkvm** [gcash/bchd#341]
https://github.com/gcash/bchd/blob/master/mining/mining.go#L289-L295

A little curious about why an extra byte added in this place, `blockchain.MinTransactionSize-tx.SerializeSize()` is enough.

Thanks.

**Comment by cpacia** [comment]
I think you're right. It can probably be changed.

**Comment by zquestz** [comment]
We should be able to check this on the blocks mined on testnet.

http://testnet.imaginary.cash/address/moPG2EANa2nSmiQ9ESSGVD7F8n8uNRVzyj

They all should be just slightly bigger than they need to be. Then we can know for sure this should remove the `-1`.

**Comment by zquestz** [comment]
Fixed in https://github.com/gcash/bchd/pull/343
