### ISSUE TITLE
Ignore unrecognized p2p messages instead of disconnecting

### ISSUE THREAD

**Issue by jtoomim** [gcash/bchd#349]
Most BCH clients will ignore any p2p messages that the client does not recognize without penalty. For example, BU:

https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/release/src/net_processing.cpp#L2014

and BCHN:

https://gitlab.com/bitcoin-cash-node/bitcoin-cash-node/-/blob/master/src/net_processing.cpp#L3647

This allows for clients to develop protocol extensions by simply creating a new message type (command) for their extension, with no need to coordinate a services bit between node implementations. It allows for completely permissionless, decentralized, and forwards-compatible code development. This is the strategy that Compact Blocks used, and is the strategy that Xthinner is using.

On the other hand, if BCHD receives an unrecognized message command, it triggers an unhandled command error:

https://github.com/gcash/bchd/blob/master/wire/message.go#L214

Followed by a disconnect:

https://github.com/gcash/bchd/blob/d21313384e570dbed2e9bd11081a0c2bc84f3593/peer/peer.go#L1499

This means that BCHD will disconnect from any node that adds new features, like all Xthinner-supporting peers, until BCHD adds code to specifically recognize and ignore those new message command types.

I hereby request that BCHD change its behavior, and stop being so xenophobic. Languages are meant to evolve and adapt. Just because someone uses some words that you don't know doesn't mean that you should stop talking to them entirely.

**Comment by cpacia** [comment]
You're right that is the behavior. Though part of the problem is nodes using new network messages while advertising a compatible protocol version. BCHD will not connect to incompatible protocol versions by default but you're right that if a node advertises compatibility but then sends incompatible messages it disconnects. This is technically a misbehavior on the part of the remote node. 

BU was doing this with the xversion message I believe so we added some stubs to work around this problem. Ideally a node would bump the version number and coordinate with other implementations if it's going to change the protocol messages. But we can look into making this change.

**Comment by jtoomim** [comment]
> Though part of the problem is nodes using new network messages while advertising a compatible protocol version

If the new messages contain optional information that can safely be ignored, then the new protocol is still compatible with the old version. Making protocol extensions backwards compatible is easy as long as clients don't behave the way BCHD currently does. I think that BCHD should assume that any messages it does not recognize were implemented in a backwards-compatible fashion.

> This is technically a misbehavior on the part of the remote node.

I don't think it's misbehavior. It's merely unspecified. I haven't seen any protocol documentation stating that commands or messages other than the ones specified are invalid messages. This suggests that those commands have unspecified meaning and/or behavior. When behavior is unspecified, implementations are free to choose whichever behavior they want for that scenario. BCHD treating an `xtrconfig` command as if it were `disconnect` is a valid choice according to what I have seen of the spec, but so is treating it as a no-op. I think no-op is better.

> Ideally a node would bump the version number and coordinate with other implementations if it's going to change the protocol messages.

Bumping version numbers enforces linearity of feature sets. Software development is not linear -- it's possible for multiple teams to independently and simultaneously develop new features. Trying to force parallel development into a linear version number scheme is bound to result in headaches.

I also think that it is important that different development teams not be able to impede each other's progress. If a team wishes to add a new feature like Avalanche or UTXO commitments and fast syncing, and if that team needs to add new protocol messages to do so, they should be able to implement those features whether or not they have the support of other development teams. Requiring coordination with all other teams before protocol messages can be added is a recipe for unnecessary conflict, stalling, and bikeshedding.

**Comment by jtoomim** [comment]
In cases where behavior is unspecified, it is often best to have your implementation perform the same or similarly to other implementations. Bitcoin Core/Satoshi client has been ignoring unknown commands since 2010, so that sets a pretty strong example.

https://github.com/bitcoin/bitcoin/blob/0a61b0df1224a5470bcddab302bc199ca5a9e356/main.cpp#L2481

It has also been argued that for anything where formal specification documentation has not been written, the code is the spec. If that is the case, then ignoring unknown commands for extensibility is the correct specified behavior. It was definitely Satoshi's intended behavior, given the comment he wrote.

I recommend that BCHD adopt the same behavior.

**Comment by zquestz** [comment]
Resolved and fix is in master for the 0.16.0 release!
