### ISSUE TITLE
Node crashes on SIGQUIT

### ISSUE THREAD

**Issue by jcramer** [gcash/bchd#350]
Using `systemctl stop bchd` to stop the process with SIGQUIT on ubuntu I'm getting the following crash:

https://pastebin.com/G2cyLr4n

Here is my system file:

```
[Unit]
Description=BCHD Bitcoin Cash Full Node
Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/usr/local/bin/bchd --txindex --addrindex --grpclisten=0.0.0.0 --utxocachemaxsize=1000 --rpccert=/root/localhost.crt --rpckey=/root/localhost.key
Type=simple
Restart=always
KillSignal=SIGQUIT

[Install]
WantedBy=multi-user.target
```

**Comment by zquestz** [comment]
Is there a reason you didn't use the service script provided on the repo? The one you are using has too short a timeout and the one we provided is tested and working fine...

**Comment by jcramer** [comment]
I wasn't aware of one in repo, let me try that.  Thanks!

**Comment by jcramer** [comment]
Works great, thanks again!
