### ISSUE TITLE
SEGV crash on fastsync'd pruned node (0.15.2, Linux x86_64)

### ISSUE THREAD

**Issue by ftrader** [gcash/bchd#355]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x837173]

goroutine 955821 [running]:
github.com/gcash/bchd/blockchain/indexers.(*CfIndex).entriesByBlockHashes(0x0, 0x14db050, 0x1, 0x1, 0xc01eb37800, 0xc015218420, 0x5, 0x5, 0x0, 0xc00066cd80, ...)
        /home/travis/gopath/src/github.com/gcash/bchd/blockchain/indexers/cfindex.go:348 +0x153
github.com/gcash/bchd/blockchain/indexers.(*CfIndex).FilterHashesByBlockHashes(...)
        /home/travis/gopath/src/github.com/gcash/bchd/blockchain/indexers/cfindex.go:400
main.(*serverPeer).OnGetCFHeaders(0xc015778380, 0xc00fdc6700, 0xc0118f81e0)
        /home/travis/gopath/src/github.com/gcash/bchd/server.go:1206 +0x2e9
github.com/gcash/bchd/peer.(*Peer).inHandler(0xc00fdc6700)
        /home/travis/gopath/src/github.com/gcash/bchd/peer/peer.go:1589 +0x1808
created by github.com/gcash/bchd/peer.(*Peer).start
        /home/travis/gopath/src/github.com/gcash/bchd/peer/peer.go:2321 +0x29f

**Comment by zquestz** [comment]
What exact args did you start bchd with?

**Comment by ftrader** [comment]
This was a running the binary release (amd64), with `--fastsync --prune`

**Comment by zquestz** [comment]
Ok, will try spinning it up. Did you have any unclean shutdowns? We have been working to find a nasty bug in the recovery code when having an unclean shutdown...

**Comment by zquestz** [comment]
So I was able to bring up a node just fine with `--fastsync --prune` on master. I sync'd to tip, then shut down, brought it back up, and everything worked as expected.

Do you have additional logs I can look at?

**Comment by ftrader** [comment]
I think this occurred on a VPS where I removed BCHD since due to repurposing the node.
I do not remember seeing any unusual messages preceding the crash.

At this point I think all I can do is run it again somewhere and see if the crash re-occurs & if I can get some logs.

**Comment by zquestz** [comment]
Any luck replicating the error? I can't seem to replicate it in normal operation. Pruned nodes seem to operate just fine for me.

**Comment by zquestz** [comment]
Any update or should I close this ticket?

**Comment by zquestz** [comment]
Going to close this. Can reopen if we get more data.
