### ISSUE TITLE
Recommended JS lib to work with BCHD

### ISSUE THREAD

**Issue by kss-espeo** [gcash/bchd#356]
Hi,
I am working on integrating my client's product with Bitcoin Cash. What I need to do is - build an unsigned transaction, apply signatures to it (offline! I need to manually apply signatures to the raw transaction) , submit it to blockchain and verify its completeness.

So far, I've been using Bitbox and bitcoin.com node provider for that. However, it seems that these are deprecated now. The problem is that Bitbox is tightly coupled with bitcoin.com node. Therefore I'm searching for a new node provider. I am considering to selfhost a BCHD node.

My question is: is there a NodeJS (preferably with Typescript) library that you recommend which can be used along with a local BCHD? I don't want to do RPC calls manually, I want a lib that wraps this.

Thanks,
KSS

**Comment by zquestz** [comment]
The most popular libraries right now are:

https://github.com/simpleledgerinc/grpc-bchrpc-node
https://github.com/simpleledgerinc/grpc-bchrpc-web

These wrap the gRPC interface. Note that the JSON-RPC is modeled after bitcoind and many libraries that wrap JSON-RPC work out of the box for bchd.

**Comment by kss-espeo** [comment]
That's exactly what I needed. Thanks!
