### ISSUE TITLE
BCHD + CPUMINER - REJECT_INVALID, reason: bad-txns-undersize

### ISSUE THREAD

**Issue by SahidMiller** [gcash/bchd#357]
Hello!

I'm looking for some help with using BCHD with CPUMiner for testnet coins, particularly because there aren't any testnet faucets available. I'm running into an issue where the peers on the BCH Network are rejecting my mined blocks and returning a "bad-txns-undersize" error although I'm using the latest from source which includes a fix for issue #341 and pull request #343. Any thoughts of how to pin this issue down?

Here's what I have from the logs:

BCHD (latest from source)
``` 
C:\Code\bch\bchd>bchd -u smiller -P <> --testnet --notls
2020-04-15 17:57:36.982 [INF] BCHD: Version 0.15.2
2020-04-15 17:57:36.983 [INF] BCHD: Loading block database from 'Bchd\data\testnet\blocks_ffldb'
2020-04-15 17:57:42.371 [INF] BCHD: Block database loaded
2020-04-15 17:57:42.421 [INF] INDX: Committed filter index is enabled
2020-04-15 17:57:42.422 [INF] CHAN: Loading block index...
2020-04-15 17:57:54.039 [WRN] CHAN: Unknown block versions are being mined, so new rules might be in effect.  Are you running the latest version of the software?
2020-04-15 17:57:54.039 [WRN] CHAN: Unknown new rules activated (bit 1)
2020-04-15 17:57:54.040 [INF] CHAN: Chain state (height 1372853, hash 00000000000000871f2b83ae0d727043f7e8c83fa647efbeeb13d1588b7553af, totaltx 63529844, work 1593125362733040794964)
2020-04-15 17:57:54.041 [INF] RPCS: RPC server listening on [::1]:18334
2020-04-15 17:57:54.041 [INF] RPCS: RPC server listening on 127.0.0.1:18334
...
2020-04-15 18:10:36.020 [INF] SYNC: Syncing to block height 1372858 from peer 159.65.163.15:18333
2020-04-15 18:10:36.487 [INF] SYNC: New valid peer <> (outbound) (/Bitcoin ABC/)
2020-04-15 18:25:09.324 [INF] RPCS: Accepted block 000000006570e06c7c700a3f1afd8e6d9f547aaa97f4dba1a03af1ea70d89a31 via submitblock
2020-04-15 18:25:09.557 [WRN] PEER: Received reject message from peer <> (outbound), code: REJECT_INVALID, reason: bad-txns-undersize
```

CPUMiner (3.3.8)
```
[2020-04-15 18:25:06] Current block is 1372859
[2020-04-15 18:25:06] CPU #5: 13.50 MH, 2666.58 kH/s
[2020-04-15 18:25:06] CPU #4: 12.60 MH, 2468.67 kH/s
[2020-04-15 18:25:06] CPU #2: 13.69 MH, 2674.66 kH/s
[2020-04-15 18:25:06] CPU #3: 13.84 MH, 2718.93 kH/s
[2020-04-15 18:25:06] CPU #0: 12.69 MH, 2485.16 kH/s
[2020-04-15 18:25:06] CPU #6: 13.91 MH, 2754.26 kH/s
[2020-04-15 18:25:07] CPU #1: 13.51 MH, 2627.12 kH/s
[2020-04-15 18:25:09] CPU #7: 8722.11 kH, 2783.06 kH/s
[2020-04-15 18:25:09] accepted: 1/1 (100%), 102.46 MH, 21.18 MH/s yes!
```

**Comment by zquestz** [comment]
Any way for you to provide the raw transaction so we can look at it?

Also there is a testnet faucet now! https://faucet.fullstack.cash/

**Comment by SahidMiller** [comment]
Wow, thank you!! It's been a frustrating 24 hours of building arcane bitcoin tools on a Windows environment just to get to this moment haha.

What can I do to inspect the transaction/blocks that are submitted? the -d flag was a bit too verbose for this long running process, is there another way?

Unfortunately, I actually ran into this using the release version from Nov. 2019 as well. That version didn't contain the fix and was the reason I pulled the latest after seeing the #341 issue.

**Comment by zquestz** [comment]
So to be clear the `bad-txns-undersize` message isn't from bchd at all! This is actually from a different peer, most likely an ABC node. The reason I know it isn't bchd, is that error code doesn't exist in our codebase. =)

So what I see is you submitting a block successfully in bchd, then when it goes to relay the transaction the peer says it has a transaction which is too small.

It is going to take a bit for me to replicate this setup. We will figure it out. =)

**Comment by zquestz** [comment]
The easiest way to debug is to add additional logging to submitblock and dump all the transactions that were submitted. Hopefully can put together a small patch soon to make it easier to figure out the issue.

**Comment by SahidMiller** [comment]
Yup, that's correct. Looking at the logs, it looks like BUCash nodes were disconnecting rather than rejecting with an error message like ABC nodes did.

I will go ahead and update handleSubmitBlock in the rpcserver.go with some additional logging and also for NewBlockTemplate/createCoinbaseTransaction methods on the flip side. 

BTW: Looking at the code, I realize that there's a CPUMiner instance or related code packaged with bchd! I'm not sure how to take advantage of it... and I wonder if I'm running into this error because I'm using an external instance via RPC instead?

**Comment by zquestz** [comment]
Using an external tool should be fine. Did you get a chance to add any debugging info?

**Comment by SahidMiller** [comment]
@zquestz since I put the transaction serialization in the wrong place, I only have the full serialized block that was rejected. Mind if I post it?

**Comment by zquestz** [comment]
The serialized block should be fine. We can easily write a tool to inspect that!

**Comment by SahidMiller** [comment]
Thanks! Sorry for the wall.
```0000002046c8bb64a65c03b3318216c7b1efb47813d88bac932ffb7fdf000000000000002e96dfe13b05c6dd1fc636c25cadfaf63dc99b045e7fe040419b3e306fd94a9eb0f99f5effff001d801a07cf0901000000010000000000000000000000000000000000000000000000000000000000000000ffffffff0c03d3f61407062f626368642fffffffff014008a904000000001976a9141bdf06085ac311cad249dec3f409e778066f3fb688ac000000000200000001006b470d317a5388008c8234a020e32cdb2d793682b437d3f7bcaa4d966f3af103000000fdfd00004830450221008b147e6d562c74be9befebe9e169685b34fba93d5f95ad6ef2befe860fec75740220641efd789d42f681678314d0548d5fa647542215c441f544e0444127f969dce341473044022045afdb049da4df4c8febb358fb86e99fbad907b265f24120185fe2f60b6b9b5f022029749cb88f6fb484293566c107ed7da3561ce7d04a2092298763e357c9dc8a1a414c69522102325d5ee24381373c2c51ca24124dff75202c93e099bde40ed3d259099a0ca4842102d2391e2d4ac67f58138fbb796747f371b7f367be4b33fd89568c8975f0038a2c21033357acd42d0b2e80f39354e1eaf0ea757544c167f8cfe8758c3084b958aefe5953aeffffffff05fb1700000000000017a9144317fab085c437a18e1f656c193d6062a917df4d87fb1700000000000017a9147afcdfcff9ca156e73e67128791e0bcc908e251e87fb1700000000000017a914ac0b0b53ecb88eb9e61cc583588877fac167067087fb1700000000000017a914edf646347635bd1c7acfd29c893a994257d73d1287c45921020000000017a91424f6073338cc14687a6ea0bfae65328f7520591087d3f614000100000001607eca04cbc38bb6ada53c924ba04ad5f5dbd120c4552d29bb15665852db19ef010000006a47304402206e28e3f7a98e3416e32181e9d4b21a207292d5da8fd381ac5b99615230941459022023887479134948e0fa6ba4488df8282899a49e94e6f0bf235569615a893b8d1f4121029e0c7d24669ac790c91c5395e06b8dafd2b184e77812f5896919ccc5af8145bfffffffff02a0860100000000001976a9141e9c90136a0fdf43863702fd60ebb3be77e7ee7e88ac782ec106000000001976a914def06f92022f0f8ebc5f318daa8ffb5496b1d0df88ac000000000200000003372d998e1f0fbf3a496361db5a5b64ff25bd616aeca88daac68947ba8541888e010000006a47304402201aa04db20eee11e70641a8adfbc37425b97a3cc0d3f84c64ec7f7dacb45235ab0220359ecdedf17ba1aa5d6bef792cb8c862bd42ba12a141cbfba4e9d573dd03ae3e412102617a40d31c904b7d406a3cea935bdec960a895eee58c035e02501930ba808ef5feffffff36e26bd760e2183e0cf3cab92b46f668958b8542e10d11dd3517f33d5b465d72010000006b4830450221008d17bbf8736482054a1eff23027fd404d999e0f7ca8eafb54875e22e241ae4d30220554ea773f899e9e447dc4d00e391e548315df3de2eb5766e2756bc4d523e01444121024cf389e2a3fc3b15dc6a2f019669edaa610326fa97e4c6f60e95b6691ced2ac0feffffff36e26bd760e2183e0cf3cab92b46f668958b8542e10d11dd3517f33d5b465d72000000006a47304402203950eef5825d1788ffb1b95ed2a1a8fe89f37e8131ebdbab016308ee24c8f1f202203690c8244115f6e1b7cb320d1495f4e9f4e4e83660336be23a93244933cc13b4412102414b15c9eda605582b5ab13077b1b96ee137add5fd4dca9702cc595ba2f68ae1feffffff02e8030000000000001976a914092afee85c66550b0855472016ee8f0adf29e0bb88ace8030000000000001976a914417946630e0903d594ea97c9b57ada53d540c2cc88acccf614000100000002d94a2e12237c29ca0bd7cd426d4877259874a8f774ebe798ec54cae5f4b3fe59020000006a473044022069dbca200aac0ea1c3e78ed309d84278647ae15cef4c9a4e711fa2571bdc72120220699616918eb7ddce5d3d691b46f4e6cbee5863de35b24f3d7288d7af91baa08d4121021bc82ce61570d11fd1023960a385dc27c3441ec806511523aa55ec7532b4b658ffffffffd4329b57a0a28a84805bd5efa8b5f3d2b72b11ec433cf6216d98d06b6dfefb77010000006b483045022100c09c2453e1a8c18057f2279559d6f2e2ce0974d2aa77b9eb48a57cf14ae1e83b02203f0a7ecb35559d5b2baea9dcb8284c5b6258f8bb9c4665a0668b4b2bcfdc79374121021bc82ce61570d11fd1023960a385dc27c3441ec806511523aa55ec7532b4b658ffffffff02803801000000000017a914a34ed11449cfa299db29d53bc137f3cbf6c78605873d700000000000001976a914d62682215be9bdb7f35cfb81a03892c730ea094488ac000000000100000002d94a2e12237c29ca0bd7cd426d4877259874a8f774ebe798ec54cae5f4b3fe59030000006b483045022100f90e20973a386a5ccc325e941b3684419daa34fe09ad35c75b492e294b38a804022050c6da4da827ae7bfb1152663fa03c905d206c2997f50972b286cbaab7cc8f48412102e5cca8b059b2b46e5c8832c722b5d4306b710f5989bd9b3af064ba17ef38e041ffffffff89bbf52c54ce0b9c2a2daf058ce1c653e8c8ef02c05d160f6b25411aa6298b89010000006a473044022049d7037e68c7d3ecdbdf0892ccd2787d5f7901e7d99f8adfb12ea691a4dad91b0220405c489f657c4957db6cb6d55c9f62779cd97aed98f581f0c1327f4c636ed165412102e5cca8b059b2b46e5c8832c722b5d4306b710f5989bd9b3af064ba17ef38e041ffffffff02803801000000000017a9143f93f0da2c9238c810f3fe4ad95d209144bf363a87df4a0000000000001976a9140df239e50227b9f5e1c69ff8939f3625e9cfdd2088ac00000000010000000325e1f6783123866d54b871179910d91772dcca1a6818ad0e47192e67e1c8c837000000006b4830450221009e9e1c575d38824f3b3a3aa73d190c9c89e3f9a1cebeae5d3273ed4ff4766cbd02203e399c27d2c991af3fa1c651e1d098d5d4ba4a80a79dae0e3b821c1046d92d214121020a688583384fc1cac297a472eda4da6e4e9ad868cdcce6bd39f83e37df28f980ffffffffedce310920c0e5511d781d24bf0a2891d4555ffa02435ed4848c0ae9dbae4145010000006b48304502210082c855221876e6828cc0cca1213735310e0d2205f5cba97674487a981edfd3f902205ea81fcbfb10964bbf4b87609110312dadad622b2af39ac3f4d88c18219d89c04121020a688583384fc1cac297a472eda4da6e4e9ad868cdcce6bd39f83e37df28f980ffffffffd94a2e12237c29ca0bd7cd426d4877259874a8f774ebe798ec54cae5f4b3fe59010000006a47304402202eec95c6b4f4e3a211264e72469823658a7c95edf847d2ea8ab03093d37dbcf202201776f66bf5fbaad89c2fa0b14e3f43128fe35a35d507f869e50671cf9444ea774121020a688583384fc1cac297a472eda4da6e4e9ad868cdcce6bd39f83e37df28f980ffffffff02701101000000000017a9145e3a6f3aa023645b473746e6b1f5d6694cb1f8eb87dbb00100000000001976a9141e9c90136a0fdf43863702fd60ebb3be77e7ee7e88ac00000000010000000193d9884b3bf792464338245d57dad3f287dd776dcb71727a5a859085f6dc1ace010000006a4730440220565fa15b6281f9cad30c7bfe356e4316192d5e7c1e1de0d9b626589756ffea9a02206c523222ae38c09ddf9f1b40d3806eac98bada4ae836841e742acb2642c44c454121029e0c7d24669ac790c91c5395e06b8dafd2b184e77812f5896919ccc5af8145bfffffffff02a0860100000000001976a914232caeaf56c568fa432ceeeea0be74b07212168e88ac28dcc206000000001976a914def06f92022f0f8ebc5f318daa8ffb5496b1d0df88ac0000000001000000039bfe37034db3f7e772d8dff2dddd414bf79de55377a09d7e0d0173f697e9a920010000006b483045022100c1de3020229c872326e2f250a489f69083d0bbfff040517fedf707ac680a2509022006bbd74ed28627231dcce4367b1808aae67c6acccbcdbf1e344c544c38ebf2d8412102dfe35bb25868b0e98fd507f47afa86f38be3bacefb472d0748435b1550fb9104ffffffffd94a2e12237c29ca0bd7cd426d4877259874a8f774ebe798ec54cae5f4b3fe59000000006a47304402202accfda98041ec465df2130c56e6a326840de7ef907cf22ebc4fb55a73ff01d8022048a0ea5c206bf78960d1ce0b3e1227bc51eec00be41642a02796acf1b4866210412102dfe35bb25868b0e98fd507f47afa86f38be3bacefb472d0748435b1550fb9104ffffffff607eca04cbc38bb6ada53c924ba04ad5f5dbd120c4552d29bb15665852db19ef000000006b4830450221009e330980d843cbcba772191aa6f5c5fedebd62a678256866a1c4212aba4e92340220559fbf56aa89c04aca377cc1d62d0ef0e2d017e77c742d09d51b65aef5fae36b412102dfe35bb25868b0e98fd507f47afa86f38be3bacefb472d0748435b1550fb9104ffffffff02701101000000000017a91424a63922c0ba300355f9ca9bc2a10c306009dda38764d00100000000001976a914232caeaf56c568fa432ceeeea0be74b07212168e88ac00000000```

**Comment by zquestz** [comment]
Sorry for the delay, digging into this now =)

**Comment by zquestz** [comment]
So that block appears to have a coinbase transaction that is 97 bytes. The minimum on BCH is 100 bytes.

The code to check it, just for record can be found at https://play.golang.org/p/sSaafQogN87

```
package main

import (
	"bytes"
	"encoding/hex"
	"fmt"

	"github.com/gcash/bchd/wire"
)

func main() {
	b, _ := hex.DecodeString("0000002046c8bb64a65c03b3318216c7b1efb47813d88bac932ffb7fdf000000000000002e96dfe13b05c6dd1fc636c25cadfaf63dc99b045e7fe040419b3e306fd94a9eb0f99f5effff001d801a07cf0901000000010000000000000000000000000000000000000000000000000000000000000000ffffffff0c03d3f61407062f626368642fffffffff014008a904000000001976a9141bdf06085ac311cad249dec3f409e778066f3fb688ac000000000200000001006b470d317a5388008c8234a020e32cdb2d793682b437d3f7bcaa4d966f3af103000000fdfd00004830450221008b147e6d562c74be9befebe9e169685b34fba93d5f95ad6ef2befe860fec75740220641efd789d42f681678314d0548d5fa647542215c441f544e0444127f969dce341473044022045afdb049da4df4c8febb358fb86e99fbad907b265f24120185fe2f60b6b9b5f022029749cb88f6fb484293566c107ed7da3561ce7d04a2092298763e357c9dc8a1a414c69522102325d5ee24381373c2c51ca24124dff75202c93e099bde40ed3d259099a0ca4842102d2391e2d4ac67f58138fbb796747f371b7f367be4b33fd89568c8975f0038a2c21033357acd42d0b2e80f39354e1eaf0ea757544c167f8cfe8758c3084b958aefe5953aeffffffff05fb1700000000000017a9144317fab085c437a18e1f656c193d6062a917df4d87fb1700000000000017a9147afcdfcff9ca156e73e67128791e0bcc908e251e87fb1700000000000017a914ac0b0b53ecb88eb9e61cc583588877fac167067087fb1700000000000017a914edf646347635bd1c7acfd29c893a994257d73d1287c45921020000000017a91424f6073338cc14687a6ea0bfae65328f7520591087d3f614000100000001607eca04cbc38bb6ada53c924ba04ad5f5dbd120c4552d29bb15665852db19ef010000006a47304402206e28e3f7a98e3416e32181e9d4b21a207292d5da8fd381ac5b99615230941459022023887479134948e0fa6ba4488df8282899a49e94e6f0bf235569615a893b8d1f4121029e0c7d24669ac790c91c5395e06b8dafd2b184e77812f5896919ccc5af8145bfffffffff02a0860100000000001976a9141e9c90136a0fdf43863702fd60ebb3be77e7ee7e88ac782ec106000000001976a914def06f92022f0f8ebc5f318daa8ffb5496b1d0df88ac000000000200000003372d998e1f0fbf3a496361db5a5b64ff25bd616aeca88daac68947ba8541888e010000006a47304402201aa04db20eee11e70641a8adfbc37425b97a3cc0d3f84c64ec7f7dacb45235ab0220359ecdedf17ba1aa5d6bef792cb8c862bd42ba12a141cbfba4e9d573dd03ae3e412102617a40d31c904b7d406a3cea935bdec960a895eee58c035e02501930ba808ef5feffffff36e26bd760e2183e0cf3cab92b46f668958b8542e10d11dd3517f33d5b465d72010000006b4830450221008d17bbf8736482054a1eff23027fd404d999e0f7ca8eafb54875e22e241ae4d30220554ea773f899e9e447dc4d00e391e548315df3de2eb5766e2756bc4d523e01444121024cf389e2a3fc3b15dc6a2f019669edaa610326fa97e4c6f60e95b6691ced2ac0feffffff36e26bd760e2183e0cf3cab92b46f668958b8542e10d11dd3517f33d5b465d72000000006a47304402203950eef5825d1788ffb1b95ed2a1a8fe89f37e8131ebdbab016308ee24c8f1f202203690c8244115f6e1b7cb320d1495f4e9f4e4e83660336be23a93244933cc13b4412102414b15c9eda605582b5ab13077b1b96ee137add5fd4dca9702cc595ba2f68ae1feffffff02e8030000000000001976a914092afee85c66550b0855472016ee8f0adf29e0bb88ace8030000000000001976a914417946630e0903d594ea97c9b57ada53d540c2cc88acccf614000100000002d94a2e12237c29ca0bd7cd426d4877259874a8f774ebe798ec54cae5f4b3fe59020000006a473044022069dbca200aac0ea1c3e78ed309d84278647ae15cef4c9a4e711fa2571bdc72120220699616918eb7ddce5d3d691b46f4e6cbee5863de35b24f3d7288d7af91baa08d4121021bc82ce61570d11fd1023960a385dc27c3441ec806511523aa55ec7532b4b658ffffffffd4329b57a0a28a84805bd5efa8b5f3d2b72b11ec433cf6216d98d06b6dfefb77010000006b483045022100c09c2453e1a8c18057f2279559d6f2e2ce0974d2aa77b9eb48a57cf14ae1e83b02203f0a7ecb35559d5b2baea9dcb8284c5b6258f8bb9c4665a0668b4b2bcfdc79374121021bc82ce61570d11fd1023960a385dc27c3441ec806511523aa55ec7532b4b658ffffffff02803801000000000017a914a34ed11449cfa299db29d53bc137f3cbf6c78605873d700000000000001976a914d62682215be9bdb7f35cfb81a03892c730ea094488ac000000000100000002d94a2e12237c29ca0bd7cd426d4877259874a8f774ebe798ec54cae5f4b3fe59030000006b483045022100f90e20973a386a5ccc325e941b3684419daa34fe09ad35c75b492e294b38a804022050c6da4da827ae7bfb1152663fa03c905d206c2997f50972b286cbaab7cc8f48412102e5cca8b059b2b46e5c8832c722b5d4306b710f5989bd9b3af064ba17ef38e041ffffffff89bbf52c54ce0b9c2a2daf058ce1c653e8c8ef02c05d160f6b25411aa6298b89010000006a473044022049d7037e68c7d3ecdbdf0892ccd2787d5f7901e7d99f8adfb12ea691a4dad91b0220405c489f657c4957db6cb6d55c9f62779cd97aed98f581f0c1327f4c636ed165412102e5cca8b059b2b46e5c8832c722b5d4306b710f5989bd9b3af064ba17ef38e041ffffffff02803801000000000017a9143f93f0da2c9238c810f3fe4ad95d209144bf363a87df4a0000000000001976a9140df239e50227b9f5e1c69ff8939f3625e9cfdd2088ac00000000010000000325e1f6783123866d54b871179910d91772dcca1a6818ad0e47192e67e1c8c837000000006b4830450221009e9e1c575d38824f3b3a3aa73d190c9c89e3f9a1cebeae5d3273ed4ff4766cbd02203e399c27d2c991af3fa1c651e1d098d5d4ba4a80a79dae0e3b821c1046d92d214121020a688583384fc1cac297a472eda4da6e4e9ad868cdcce6bd39f83e37df28f980ffffffffedce310920c0e5511d781d24bf0a2891d4555ffa02435ed4848c0ae9dbae4145010000006b48304502210082c855221876e6828cc0cca1213735310e0d2205f5cba97674487a981edfd3f902205ea81fcbfb10964bbf4b87609110312dadad622b2af39ac3f4d88c18219d89c04121020a688583384fc1cac297a472eda4da6e4e9ad868cdcce6bd39f83e37df28f980ffffffffd94a2e12237c29ca0bd7cd426d4877259874a8f774ebe798ec54cae5f4b3fe59010000006a47304402202eec95c6b4f4e3a211264e72469823658a7c95edf847d2ea8ab03093d37dbcf202201776f66bf5fbaad89c2fa0b14e3f43128fe35a35d507f869e50671cf9444ea774121020a688583384fc1cac297a472eda4da6e4e9ad868cdcce6bd39f83e37df28f980ffffffff02701101000000000017a9145e3a6f3aa023645b473746e6b1f5d6694cb1f8eb87dbb00100000000001976a9141e9c90136a0fdf43863702fd60ebb3be77e7ee7e88ac00000000010000000193d9884b3bf792464338245d57dad3f287dd776dcb71727a5a859085f6dc1ace010000006a4730440220565fa15b6281f9cad30c7bfe356e4316192d5e7c1e1de0d9b626589756ffea9a02206c523222ae38c09ddf9f1b40d3806eac98bada4ae836841e742acb2642c44c454121029e0c7d24669ac790c91c5395e06b8dafd2b184e77812f5896919ccc5af8145bfffffffff02a0860100000000001976a914232caeaf56c568fa432ceeeea0be74b07212168e88ac28dcc206000000001976a914def06f92022f0f8ebc5f318daa8ffb5496b1d0df88ac0000000001000000039bfe37034db3f7e772d8dff2dddd414bf79de55377a09d7e0d0173f697e9a920010000006b483045022100c1de3020229c872326e2f250a489f69083d0bbfff040517fedf707ac680a2509022006bbd74ed28627231dcce4367b1808aae67c6acccbcdbf1e344c544c38ebf2d8412102dfe35bb25868b0e98fd507f47afa86f38be3bacefb472d0748435b1550fb9104ffffffffd94a2e12237c29ca0bd7cd426d4877259874a8f774ebe798ec54cae5f4b3fe59000000006a47304402202accfda98041ec465df2130c56e6a326840de7ef907cf22ebc4fb55a73ff01d8022048a0ea5c206bf78960d1ce0b3e1227bc51eec00be41642a02796acf1b4866210412102dfe35bb25868b0e98fd507f47afa86f38be3bacefb472d0748435b1550fb9104ffffffff607eca04cbc38bb6ada53c924ba04ad5f5dbd120c4552d29bb15665852db19ef000000006b4830450221009e330980d843cbcba772191aa6f5c5fedebd62a678256866a1c4212aba4e92340220559fbf56aa89c04aca377cc1d62d0ef0e2d017e77c742d09d51b65aef5fae36b412102dfe35bb25868b0e98fd507f47afa86f38be3bacefb472d0748435b1550fb9104ffffffff02701101000000000017a91424a63922c0ba300355f9ca9bc2a10c306009dda38764d00100000000001976a914232caeaf56c568fa432ceeeea0be74b07212168e88ac00000000")
	block := &wire.MsgBlock{}
	block.BchDecode(bytes.NewReader(b), wire.ProtocolVersion, wire.BaseEncoding)
	fmt.Println("SIZE OF COINBASE", block.Transactions[0].SerializeSize())
}
```

**Comment by zquestz** [comment]
Also, put in a few more fixes as I was digging into the code. Now your local node won't accept the bad block! https://github.com/gcash/bchd/pull/362

**Comment by zquestz** [comment]
Ok, fixes have merged into master. If you want to cpu mine it works directly in bchd. =)
