### ISSUE TITLE
Unrecoverable inconsistent state after hard shutdown, null pointer reference

### ISSUE THREAD

**Issue by SahidMiller** [gcash/bchd#358]
After submitting a block that was rejected and doing a hard shutdown, I ran into this error due to the inconsistent state. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x820d28]

goroutine 1 [running]:
github.com/gcash/bchd/blockchain.(*utxoCache).InitConsistentState(0xc0005a4720, 0xc00b45eff0, 0x0, 0xc0000342a0, 0x4600123100, 0xc0001c3198)
         .../bchd/blockchain/utxocache.go:712 +0x4b8
github.com/gcash/bchd/blockchain.New(0xc0001c38e8, 0xc, 0xc, 0x0)
          .../bchd/blockchain/chain.go:2300 +0x77e
main.newServer(0xc0001858e0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf38b00, ...)
         .../bchd/server.go:3195 +0xa37
main.bchdMain(0x0, 0x0, 0x0)
         .../bchd/bchd.go:153 +0x74a
main.main()
        .../bchd/bchd.go:335 +0xe5
```
Here's the relevant code:
```
	// Even though this should always be true, make sure the fetched hash is in
	// the best chain.
	var statusNode *blockNode
	var statusNodeNext *blockNode // the first one higher than the statusNode
	attachNodes := list.New()
	for node := tip; node.height >= 0; node = node.parent {
		if node.hash == *statusHash {
			statusNode = node
			break
		}
		attachNodes.PushFront(node)
		statusNodeNext = node
	}
```

After making a quick patch myself, I still run into another error when booting: `Unable to start server on [:18333]: assertion failed: last utxo consistency status contains hash that is not in best chain: 000000000e7ed11c51590229ce90c77a978813b49e6e1962d7b89c11264f9359`

`000000000e7ed11c51590229ce90c77a978813b49e6e1962d7b89c11264f9359` is the txid for a block I tried to submit a few hours before mining the block that I hard exited resulting in this error.

**Comment by cpacia** [comment]
Thanks. We've got to take a deep look at the recovery code as it doesn't work every time. 

If you want to recover the node restart with `--reindexchainstate` and then after it finishes use `bchctl reconsiderblock <first rejected block hash>`

**Comment by SahidMiller** [comment]
Sorry @cpacia, I've been running with the reindexchainstate option and forgot to mention it!
 
bchd is entering `InitConsistentState` with or without `--reindexchainstate` and then failing at the snippet above due to a null `node.parent` and/or `statusNode`. I'm unsure what to do to get back to the happy path.

**Comment by SahidMiller** [comment]
So to reiterate `--reindexchainstate` throws the same error of `invalid memory address or nil pointer dereference` so my node can't be booted up.

**Comment by SahidMiller** [comment]
Oh, the real error is the assertion for statusNode `last utxo consistency status contains hash that is not in best chain: 000000000e7ed11c51590229ce90c77a978813b49e6e1962d7b89c11264f9359`

**Comment by zquestz** [comment]
Yeah, this was because we accepted an invalid block into the chain. My latest PR changes make sure this can't happen again, aka this bug should no longer happen.

We are still investigating other recovery issues, but this one should not plague anyone again. =)

**Comment by SahidMiller** [comment]
@zquestz Anyway I can still make use of my already downloaded blocks? It's many gigs worth (testnet)  

Also, I had to make a small change to the loop `for node := tip; node.height >= 0; node = node.parent { ... }`  since node.parent for `block 0` was giving the null pointer error and hiding the real error message.

**Comment by zquestz** [comment]
Unfortunately I am not sure the best way to recover your existing install. I would definitely recommend resyncing. The code paths are quite dangerous to adjust, and it most likely will present errors later.

**Comment by SahidMiller** [comment]
I just need more background information on what a status node is and why my "best" chain doesn't contain it. Do you have any idea whether it's the status node that's the problem or my "best" chain?

Also, what do you think is the best way to inspect and change the ffl database?

**Comment by zquestz** [comment]
The status node is the node that is known good to your install. The problem is that a bad block was saved as your status node, because the validations in submitBlock didn't catch the bad coinbase transaction (It was < 100 bytes).

When you submitted the block it should have rejected it (will now), but since it accepted it, it saved the state of your chain as including that bad block. You might be able to launch bchd with `--reindexchainstate` to try and fix it, but I am not sure it will recover.
