### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by cpacia** [gcash/bchd#36]
If any web developers/designers out there would like to contribute a static website to promote the software and host the binaries that would be much appreciated.

**Comment by zquestz** [comment]
Do you have a domain name already?

**Comment by romainPellerin** [comment]
I could contribute a template extracted from eminent.ly website if you want. That's a React-js one. Or we can just build a GitHub page like we did for chopsticks.cash, that works pretty well and it's deploy on git push.

**Comment by cpacia** [comment]
@zquestz I do not have a domain.

**Comment by zquestz** [comment]
I have just purchased bchd.cash. That way no one else grabs it. =)

**Comment by cpacia** [comment]
nice

**Comment by zquestz** [comment]
Basic website is now up at bchd.cash. Also the code is open source at https://github.com/gcash/bchd-web for anyone to make changes and improvments!
