### ISSUE TITLE
ZMQ support

### ISSUE THREAD

**Issue by thomasxnguy** [gcash/bchd#370]
Bchd has gRPC API to provide strong support for publish/subscribe and request/reply patterns. However its lacking support for push/pull pattern. It is particularly useful for service that needs to process every tx messages in order to scale properly (message broker). 

BTC has support for ZMQ, and some other implementation of BCH node as well. It would be nice to have it for bchd

**Comment by cpacia** [comment]
Well a large part of the impetus for gRPC was so we don't have to include a large C dependency in code to support ZMQ. So I think we're unlikely to ever include it. 

What is the use case for the push/pull, some kind of load balancer?

**Comment by thomasxnguy** [comment]
Yes exactly, I would need a broker to dispatch the load to parallelise my job.

Ok I understand the design choice. I can make it outside the node with a little loss of efficiency.
I can close the issue if its the last word

**Comment by cpacia** [comment]
Yeah I think for now we're not going to address it. It's possible some kind of push/pull functionality could be built on top of gRPC but no plans for now.
