### ISSUE TITLE
Failures responding to getcfilters for large blocks

### ISSUE THREAD

**Issue by justusranvier** [gcash/bchd#378]
I've identified several testnet blocks whose cfilters are impossible to fetch via the p2p protocol:

1307544, 1307676, 1307679, 1307680, 1307685, 1307690, 1307691, 1307723, and possibly others are affected.

Sending a BIP-157 getcfilters request for a range containing any of those blocks will cause bchd to drop the connection.

All the blocks I've identified problems with are notable for being unusually large, so it seems like an error caused by an assumption about the maximum size of cfilters and/or their associated messages which is not valid for blocks near 32 MB.

**Comment by zquestz** [comment]
Thanks for the fix. :-)
