### ISSUE TITLE
Implement persistent connections for HTTP RPC (JSON)

### ISSUE THREAD

**Issue by cculianu** [gcash/bchd#380]
It would be really nice if bchd's HTTP RPC server (JSON RPC) supported HTTP/1.1 persistent connections as per the RFC: https://tools.ietf.org/html/rfc2616#section-8.1

All of the other bitcoind node implementations support this. (Core, ABC, BCHN, BU, Flowee, etc).

Instead, bchd closes the connection after each request: https://github.com/gcash/bchd/blob/87e4c5c4fc131b1683fe2dfbfcb2c83561a8e282/rpcserver.go#L4553

This is a deal-breaker for Fulcrum being able to support bchd properly.  On block chain synch, millions of RPC commands need to be issued potentially.  Being forced to re-open the connection each time severely impacts performance to the point where I don't think it's worth it to support bchd, unfortunately.

Please consider it.

**Comment by zquestz** [comment]
The code for the rpc server is about 5 years old, and explicitly avoids using Go's http handling for persistent connections. The changes shouldn't be that large, but will require some testing to make sure we don't regress any behavior.

This would be a great item for someone to pick up that is new to bchd, but been using Go for a while. =)

**Comment by cculianu** [comment]
Thanks for being amenable to this change, man. It would make Fulcrum's life easier (and any other such similar service).
