### ISSUE TITLE
Questions about bchd HTTP JSON-RPC quirks

### ISSUE THREAD

**Issue by cculianu** [gcash/bchd#385]
So, using Josh's patch:  https://github.com/gcash/bchd/pull/384 , I was able to get Fulcrum to talk to bchd and use it to serve SPV data to Electron Cash.  Yay!

I have 3 questions about some quirks I observed (ones that I had to write workarounds for here: https://github.com/cculianu/Fulcrum/pull/33.

1. bchd seems to refer to the networks as "mainnet" and "testnet3", whereas the bitcoind's just call them "main" and "test".  Is this intentional?  Any chance I can convince you to change it? (Probably not, since it seems the rest of your code depends on this naming scheme).
2. bchd seems to have a particular quirk with the `getrawtransaction` RPC call.  It expects an `int` argument for parameter #2 (`verbose`).  The other calls like `getrawmempool` take `bool` for the `verbose` arg (and reject `int`!).  ABC, BCHN, etc bitcoind takes `bool` for all such args.  This quirk required a workaround.  Any chance I can convince you guys to accept **either** `bool` or `int` here so I can do away with this special-case?
3. The integer `"version"` returned from `getnetworkinfo` is encoded in a strange way.  Can you explain how to decode it? I see the go line in `version.go` is: `return 2 ^ AppMajor*3 ^ AppMinor*5 ^ AppPatch` <-- what is that??!  ABC, BCHN, BU, and others all encode it much differently.  I can't even understand how to unpack that value (maybe I am just tired). Can you tell me how to reverse that transformation?  It seems.. "lossy" because `*3` and `*5` are not really on any PoT boundary... Is this intentional?  Can this be fixed?  Any info is appreciated...

**Comment by zquestz** [comment]
1.  Not going to change the naming, this will make it much harder to accept backports and there are a lot of touch points.  Also I see you already fixed it in fulcrum. =)

2. It is difficult for us to support both, but I think there is a good argument we should use the same args as ABC and BCHN. We should probably update getrawtransaction to use a bool for verbosity.

3. This was how it was done in btcd, I am all for changing this behavior to match other node responses. I agree the current value doesn't make much sense. Maybe parse subversion. for now?

@cpacia do you have any feedback on this?

**Comment by cculianu** [comment]
1. ok
2. Oh.. I guess you use some JSON schema thing? Well I mean my workaround works.. but yeah would be nice to have it work like the other bitcoind's. I'd hate for you to change it and make other code break tho. Your call.
3. Ok, fair enough. I'll parse subversion.

**Comment by zquestz** [comment]
Fixed version in https://github.com/gcash/bchd/pull/386

**Comment by cculianu** [comment]
Do you think there's a strong chance this change (or something equivalent) will make it into mainline bchd? I want to bullet-point in my next fulcrum release that "bchd support is ready!"... but I don't know if that's premature as of now.

Thanks.

**Comment by zquestz** [comment]
So the only remaining item is #2 and I am going to try and get that tackled, or maybe @JettScythe could get it fixed

**Comment by zquestz** [comment]
So I got bored and did this tonight. =)

https://github.com/gcash/bchd/pull/391

**Comment by cculianu** [comment]
Ok Cool. I'll close this now.
