### ISSUE TITLE
BCHD as local TestNet

### ISSUE THREAD

**Issue by readcash** [gcash/bchd#395]
Hi guys! You might have heard about https://mainnet.cash/ .. assuming this gets funded I want to make sure that every function that we develop works. That requires a testsuite of course. That ideally requires... well, a network to test against. 

And BCHD for me is the prime candidate to develop against and thereby for running integration tests. I'm pretty happy with it on read.cash and assuming you'll implement SLP too, that would be super cool!

How hard would it be to create something like a flag, maybe like this: 

    ./bchd -isolated-testnet=12345,bitcoincash:qq2346,10000,bitcoincash:qv9734,20000

 which would start BCHD in an isolated mode, where block 12345 was just mined and current fork rules for block 12346 apply, address `bitcoincash:qq2346` has 10000 satoshis, and address `bitcoincash:qv9734` has 20000 satoshis (well, I shortened the addresses, but you get the idea). After that everything works as if this was the real node, except that it doesn't try to sync with anything and the node doesn't attempt to initiate any connection to others. 

The block height is needed so that we can test against each set of rules before and after the fork (so that for example now we could test for current rules and rules of the upcoming fork to ensure compatibility).

Ideally, maybe also add some call to "virtually" mine everything in the current mempool into a block (to test confirmations, etc...)

This would allow us to run the BCHD node to test against in fully isolated mode, i.e to run the testsuite to make sure we're 100% compatible and restart/reload it each time the test suite runs. I think a command to reload (i.e. to reset to original state) would be even more cool, but it's certainly nice-to-have, not a necessity.

Additional benefit would be for other developers - they won't have to rely on TestNet being available and TestNet faucets - they'll just launch BCHD locally with this flag and develop against it. We'll certainly include BCHD in the tutorials in that case. I think it's an ideal candidate - since it's Go - single binary - download and run.

How hard would it be to implement? Could you do it? If you don't have time - could you give some pointers/potential pitfalls on how to implement it so that maybe we can do a PR using some external Go developer?  

Thanks!

**Comment by cpacia** [comment]
Would regtest work for this?

**Comment by readcash** [comment]
I tried Googling `bchd regtest`, but I could only see that BCHD has this flag. Could you please clarify what it does?

**Comment by readcash** [comment]
Ok, found something about regtest here: https://bitcoinj.github.io/testing

So, does something like this work in BCHD?

> Then you can send some test coins to your app like this:
> 
> `./bitcoin-cli -regtest sendtoaddress <address of your app goes here> 10.0`
> `./bitcoin-cli -regtest generate 1`

**Comment by cpacia** [comment]
Yup. You should be able to create multiple nodes and link them if you want to do that. Though a single node usually works fine. 

A couple of the hardforks active at height 1000.

**Comment by readcash** [comment]
Cool! Thanks! 

I've run `./bchd --regtest`, then I try to do `./bchctl generate 101` and I'm getting `
open .../Library/Application Support/Bchd/rpc.cert: no such file or directory`

I'm on Mac.

Directory `.../Library/Application Support/Bchd` exists, but there's no rpc.cert in it. 

I found this: https://gist.github.com/cpacia/82ba4859b63193e48dd50b494c129d7b , but it says `On the very first start bchd generates a rpc.key and rpc.cert file and puts them in the data directory.`

There's no such file in `.../Library/Application Support/Bchd` anywhere. How to generate it?

**Comment by cpacia** [comment]
you might need to use `bchctl --testnet` to use it.

**Comment by readcash** [comment]
`./bchctl --testnet generate 101` gives the same error `open .../Library/Application Support/Bchd/rpc.cert: no such file or directory`

**Comment by cpacia** [comment]
So it doesn't look like the regtest reads the config file so you'll need to enter the command line flags.

`bchd --regtest --rpclisten=:18334 --rpcuser=chris --rpcpass=letmein`

`bchctl --testnet -u chris -P letmein getinfo`

**Comment by readcash** [comment]
Great! One step further 👍  Still having problems though:

```
./bchctl --testnet -u chris -P letmein generate 1
-32603: No payment addresses specified via --miningaddr

./bchctl --testnet -u chris -P letmein --miningaddr=bitcoincash:qpfhygf605q4m6stq6ujjrdhatuynhz40v5da3n4gc generate 1
unknown flag `miningaddr'

./bchctl --testnet -u chris -P letmein generate 1 --miningaddr=bitcoincash:qpfhygf605q4m6stq6ujjrdhatuynhz40v5da3n4gc
unknown flag `miningaddr'
```

**Comment by cpacia** [comment]
So `--miningaddr=` needs to be an argument to bchd not bchctl. 

But also you need to create a regtest address not a mainnet address. Regtest addresses uses `bchreg:` as the prefix and as part of the checksum.

**Comment by readcash** [comment]
Awesome! It works! Thank you, Chris!
