### ISSUE TITLE
Handle max peers from a single IP

### ISSUE THREAD

**Issue by cpacia** [gcash/bchd#40]
This comment can be found in server.go
> // TODO: Check for max peers from a single IP.

Basically we don't want a single IP to be able to eat up all available connections.

**Comment by tyler-smith** [comment]
As far as I can tell the peer store doesn't store any decent way to lookup connections by IP so I think a map of IP to connection count will need to be maintained.

**Comment by zquestz** [comment]
What values are you thinking are appropriate? Do we allow the user to override it?

**Comment by tyler-smith** [comment]
The default max connections is 125. A max-per-IP setting of 5 would mean you can connect to at least 25 different IPs. A setting of 10 would allow for at least 13 IPs.

It probably should be configurable like the max connections is.

**Comment by zquestz** [comment]
Done and merged.
