### ISSUE TITLE
Testnet in Docker

### ISSUE THREAD

**Issue by pospisil1212** [gcash/bchd#403]
Hello, I created docker image from the source. I want use a image with testnet. So I changed my bchd.conf like this: `datadir=/block/testnet
testnet=1
; Maximum allowed ban score before disconnecting and banning misbehaving peers.
; banthreshold=100
; How long to ban misbehaving peers. Valid time units are {s, m, h}.
; Minimum 1s.
; banduration=24h
; banduration=11h30m15s
; Add whitelisted IP networks and IPs. Connected peers whose IP matches a
; whitelist will not have their ban score increased.
; whitelist=127.0.0.1
; whitelist=::1
; whitelist=192.168.0.0/24
; whitelist=fd00::/16
; Disable DNS seeding for peers.  By default, when bchd starts, it will use
; DNS to query for available peers to connect with.
; nodnsseed=1
; Specify the interfaces to listen on.  One listen address per line.
; NOTE: The default port is modified by some options such as ‘testnet’, so it is
; recommended to not specify a port and allow a proper default to be chosen
; unless you have a specific reason to do otherwise.
; All interfaces on default port (this is the default):
  listen=:18333
; All ipv4 interfaces on default port:
;  listen=0.0.0.0
; All ipv6 interfaces on default port:
;   listen=::
; All interfaces on port 8333:
;   listen=:8333
; All ipv4 interfaces on port 8333:
;   listen=0.0.0.0:8333
; All ipv6 interfaces on port 8333:
;   listen=[::]:8333
; Only ipv4 localhost on port 8333:
;   listen=127.0.0.1:8333
; Only ipv6 localhost on port 8333:
;   listen=[::1]:8333
; Only ipv4 localhost on non-standard port 8336:
;   listen=127.0.0.1:8336
; All interfaces on non-standard port 8336:
;   listen=:8336
; All ipv4 interfaces on non-standard port 8336:
;   listen=0.0.0.0:8336
; All ipv6 interfaces on non-standard port 8336:
;   listen=[::]:8336
; Disable listening for incoming connections.  This will override all listeners.
; nolisten=1
; Disable peer bloom filtering.  See BIP0111.
; nopeerbloomfilters=1
; Add additional checkpoints. Format: ‘<height>:<hash>’
; addcheckpoint=<height>:<hash>
; Disable built-in checkpoints.  Don’t do this unless you know what you’re doing.
; nocheckpoints=1
; Add comments to the user agent that is advertised to peers.
; Must not include characters ‘/’, ‘:’, ‘(’ and ‘)’.
; uacomment=
; Disable committed peer filtering (CF).
; nocfilters=1
; ------------------------------------------------------------------------------
; RPC server options - The following options control the built-in RPC server
; which is used to control and query information from a running bchd process.
;
; NOTE: The RPC server is disabled by default if rpcuser AND rpcpass, or
; rpclimituser AND rpclimitpass, are not specified.
; ------------------------------------------------------------------------------
; Secure the RPC API by specifying the username and password.  You can also
; specify a limited username and password.  You must specify at least one
; full set of credentials - limited or admin - or the RPC server will
; be disabled.
 rpcuser=s,kjfno37i4hfb
 rpcpass=kauyfgw874ghskjerhgb
; rpclimituser=whatever_limited_username_you_want
; rpclimitpass=
; Specify the interfaces for the RPC server listen on.  One listen address per
; line.  NOTE: The default port is modified by some options such as ‘testnet’,
; so it is recommended to not specify a port and allow a proper default to be
; chosen unless you have a specific reason to do otherwise.  By default, the
; RPC server will only listen on localhost for IPv4 and IPv6.
; All interfaces on default port:
   rpclisten=:18334
; All ipv4 interfaces on default port:
;   rpclisten=0.0.0.0
; All ipv6 interfaces on default port:
;   rpclisten=::
; All interfaces on port 8334:
;   rpclisten=:8334
; All ipv4 interfaces on port 8334:
;   rpclisten=0.0.0.0:8334
; All ipv6 interfaces on port 8334:
;   rpclisten=[::]:8334
; Only ipv4 localhost on port 8334:
;   rpclisten=127.0.0.1:8334
; Only ipv6 localhost on port 8334:
;   rpclisten=[::1]:8334
; Only ipv4 localhost on non-standard port 8337:
;   rpclisten=127.0.0.1:8337
; All interfaces on non-standard port 8337:
;   rpclisten=:8337
; All ipv4 interfaces on non-standard port 8337:
;   rpclisten=0.0.0.0:8337
; All ipv6 interfaces on non-standard port 8337:
;   rpclisten=[::]:8337
; File containing the certificate file
; rpccert=~/.bchd/rpc.cert
; File containing the certificate key
; rpckey=~/.bchd/rpc.key
; Specify the maximum number of concurrent RPC clients for standard connections.
; rpcmaxclients=10
; Specify the maximum number of concurrent RPC websocket clients.
; rpcmaxwebsockets=25
; Max number of concurrent RPC requests that may be processed concurrently.
; rpcmaxconcurrentreqs=20
; Mirror some JSON-RPC quirks of Bitcoin Core -- NOTE: Discouraged unless
; interoperability issues need to be worked around.
; rpcquirks=1
; Use the following setting to disable the RPC server even if the rpcuser and
; rpcpass are specified above.  This allows one to quickly disable the RPC
; server without having to remove credentials from the config file.
; norpc=1
; Use the following setting to disable TLS for the RPC server.  NOTE: This
; option only works if the RPC server is bound to localhost interfaces (which is
; the default).
 notls=1
; ------------------------------------------------------------------------------
; gRPC server options - The following options control the
; *experimental* gRPC server which is used to control and query
; information from a running bchd process.
;
; NOTE: The gRPC server also uses the rpccert and rpckey options
; defined in the RPC section above.
; ------------------------------------------------------------------------------
; Add an interface/port to listen for experimental gRPC connections
; (default port: 8335, testnet: 18335).
; grpclisten=8335
; An authentication token for the gRPC API to authenticate clients.
; grpcauthtoken=<oauth2-token>
; ------------------------------------------------------------------------------
; Database Settings - The following options control the database that holds
; the block chain.
; ------------------------------------------------------------------------------
; Database backend to use for the Block Chain.
; Valid drivers: ffldb
 dbtype=ffldb
; Delete historical blocks from the chain. A buffer of blocks will be
; retained in case of a reorg.
; prune=1
; The number of blocks to retain when running in pruned mode.
; Cannot be less than 288.
; prunedepth=4320
; Rebuild the UTXO database from currently indexed blocks on disk.
; reindexchainstate=0
; The maximum size in MiB of the database cache.
; dbcachesize=500
; The number of seconds between database flushes.
; dbflushinterval=1800
; ------------------------------------------------------------------------------
; Synchronization Settings - The following options control how the node will
; synchronize its copy of the block chain.
; ------------------------------------------------------------------------------
; Sync full blocks from the last checkpoint to the tip rather than from genesis.
; fastsync=1
; ------------------------------------------------------------------------------
; Mempool Settings - The following options
; ------------------------------------------------------------------------------
; The maximum size block (in bytes) this node will accept.
; Cannot be less than 32000000.
; excessiveblocksize=32000000
; Set the minimum transaction fee to be considered a non-zero fee,
; minrelaytxfee=0.00001
; Rate-limit free transactions to the value 15 * 1000 bytes per
; minute.
; limitfreerelay=15
; Require high priority for relaying free or low-fee transactions.
; norelaypriority=0
; Minimum time between attempts to send new inventory to a connected
; peer.  Time units are accepted: ns (nanoseconds), us (microseconds),
; ms (milliseconds), s (seconds), m (minutes), h (hours).
; trickleinterval=50ms
; Limit orphan transaction pool to 100 transactions.
; maxorphantx=100
; Do not accept transactions from remote peers.
; blocksonly=1
; Relay non-standard transactions regardless of default network settings.
; relaynonstd=1
; Reject non-standard transactions regardless of default network settings.
; rejectnonstd=1
; The maximum size in MiB of the UTXO cache.
; utxocachemaxsize=450
; ------------------------------------------------------------------------------
; Optional Indexes
; ------------------------------------------------------------------------------
; Build and maintain a full hash-based transaction index which makes all
; transactions available via the getrawtransaction RPC.
 txindex=1
; Build and maintain a full address-based transaction index which makes the
; searchrawtransactions RPC available.
 addrindex=1
; ------------------------------------------------------------------------------
; Signature Verification Cache
; ------------------------------------------------------------------------------
; Limit the signature cache to a max of 50000 entries.
; sigcachemaxsize=50000
; ------------------------------------------------------------------------------
; Coin Generation (Mining) Settings - The following options control the
; generation of block templates used by external mining applications through RPC
; calls as well as the built-in CPU miner (if enabled).
; ------------------------------------------------------------------------------
; Enable built-in CPU mining.
;
; NOTE: This is typically only useful for testing purposes such as testnet or
; simnet since the difficulty on mainnet is far too high for CPU mining to be
; worth your while.
; generate=false
; Add addresses to pay mined blocks to for CPU mining and potentially in the
; block templates generated for the getblocktemplate RPC.  One address per line.
; miningaddr=1yourbitcoinaddress
; miningaddr=1yourbitcoinaddress2
; miningaddr=1yourbitcoinaddress3
; Specify the minimum block size in bytes to create.  By default, only
; transactions which have enough fees or a high enough priority will be included
; in generated block templates.  Specifying a minimum block size will instead
; attempt to fill generated block templates up with transactions until it is at
; least the specified number of bytes.
; blockminsize=0
; Specify the maximum block size in bytes to create.  This value will be limited
; to the consensus limit if it is larger than that value.
; blockmaxsize=750000
; Specify the size in bytes of the high-priority/low-fee area when creating a
; block.  Transactions which consist of large amounts, old inputs, and small
; sizes have the highest priority.  One consequence of this is that as low-fee
; or free transactions age, they raise in priority thereby making them more
; likely to be included in this section of a new block.  This value is limited
; by the blackmaxsize option and will be limited as needed.
; blockprioritysize=50000
; This is an optional value to append to the coinbase input when generating a block
; template. It defaults to /bchd/ to signal that the block was mined with bchd. If
; you do not want this functionality you can set it to and empty string.
; cbflags=/bchd/
; ------------------------------------------------------------------------------
; Debug
; ------------------------------------------------------------------------------
; Debug logging level.
; Valid levels are {trace, debug, info, warn, error, critical}
; You may also specify <subsystem>=<level>,<subsystem2>=<level>,... to set
; log level for individual subsystems.  Use bchd --debuglevel=show to list
; available subsystems.
; debuglevel=info
; The port used to listen for HTTP profile requests.  The profile server will
; be disabled if this option is not specified.  The profile information can be
; accessed at http://localhost:<profileport>/debug/pprof once running.
; profile=6061
; Write CPU profile to the specified file.
; cpuprofile=/tmp/bchd.prof`

After the chnges I restarted the container. But when I want **bchctl getinfo** it says **Post "https://localhost:8334": dial tcp 127.0.0.1:8334: connect: connection refused**
I exposed ports 8333-8334 & 18333-18334.

Do you know, what I do bad?

**Comment by zquestz** [comment]
You want to make sure to use https://localhost:18334 if you are using testnet!
