### ISSUE TITLE
Progress bar / time left prediction

### ISSUE THREAD

**Issue by readcash** [gcash/bchd#408]
Since we know the blockchain height (in blocks) and we know the current speed at which we have processed something like 1000 last blocks, it should be easy to predict approximately how much time is left to sync the whole blockchain to get some estimation how long a wait will be.

It would be cool to see something like `1 day 10 hours left` once in a while

Thanks!

**Comment by cpacia** [comment]
Part of the problem is we don't really know how big the blocks are. The validation time varies pretty widely based on how big the block is. So even knowing the number of blocks left doesn't tell us how many transactions are left to process.

**Comment by readcash** [comment]
I think that's totally understandable, but a general ballpark estimate is still better than no estimate as I see it.

**Comment by readcash** [comment]
I mean, right now, I'm syncing a node. How long will it take? Hours? Weeks? Months? I have no idea. I have calculated it manually, but a general feeling of how long is left would have been nice.
