### ISSUE TITLE
Inventory Broadcast Max

### ISSUE THREAD

**Issue by cpacia** [gcash/bchd#41]
Inventory Broadcast Max was a limit in the Core codebase that limited how may txs were relayed to other peers and thus limited the size of blocks that could be created. 

In a quick glance at the codebase I don't see the same thing in bchd, however, there is an effective equivalent in `maxInvTrickleSize` which limits the inv packet to 1000 items. And since the default trickle interval is 10 seconds, this means the node wont send out more than approximately 30mb worth of txs every 10 minutes. 

As part of the zeroconf improvement we will likely be reducing or eliminating the trickle interval so txs are relayed immediately. I'm thinking about making the default trickle interval zero and if the interval is set to zero then the trickle timer is never started and inventory is broadcast immediately. This would leave the trickle in place as a config option. This would address the limit when the interval is zero or very low but maybe we should also look into increasing `maxInvTrickleSize`.

**Comment by zquestz** [comment]
This is done. Woot.
