### ISSUE TITLE
getAddressUnspentOutputs not returning old utxos

### ISSUE THREAD

**Issue by FreeTrade** [gcash/bchd#414]
Consider address -
https://blockchair.com/bitcoin-cash/address/qzxq9l2anrd9z2ajslkhjdfggdarteyzxss9re3sg6

Should have 3 utxos -

Calling getAddressUnspentOutputs on bchd.greyh.at:8335 returns just the 2 more recent ones

When called on my local node, which is only synced upto 200,000 or so, it should just return 1, but returns 0.

My guess is BCHD not returning old utxos.

**Comment by zquestz** [comment]
I can confirm what you are seeing. I think it is because one utxo is a coinbase reward!

**Comment by zquestz** [comment]
I see the issue. We are not handling `pubkey` address types correctly. For now you can use `GetAddressTransactions` and all the transactions are there. I am looking into a fix now!
