### ISSUE TITLE
Allow separate directory/drive for raw block data (FR)

### ISSUE THREAD

**Issue by FreeTrade** [gcash/bchd#417]
The raw block data takes up a lot of space and makes the unpruned node difficult to run on machines with small SSDs.

An option to store the raw block data, .fdb files, on a different drive might help.

It's also possible the node could run/sync faster on a very large ramdisk if this separation was possible, although power failure would require a re-index.

**Comment by zquestz** [comment]
You can just create a symlink for the `blocks_ffldb` folder for now. We probably won't be tackling this in config anytime soon.
