### ISSUE TITLE
"transaction not found" despite valid tx hash

### ISSUE THREAD

**Issue by selfdrivingmenee** [gcash/bchd#427]
Using "GetRawTransactionRequest()" in Python returns a Transaction not found error despite the tx hash being valid. 

It's probably not a bug but some "quirk" in the format of the tx hash that could be better documented/included in an example. 

I.E. the txid "098cc42f3ff7b2665a50514bd1ed18234f3ddb8f45c4cf320e3b434386d5933e" is correctly found in the blockchain by blockchair.com but I can't manage to fetch it using "GetRawTransactionRequest()", that returns 

```
raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.NOT_FOUND
	details = "transaction not found"
	debug_error_string = "{"created":"@1606405751.853503338","description":"Error received from peer ipv4:x.x.x.x:8335","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"transaction not found","grpc_status":5}"

```

**Comment by cpacia** [comment]
See here: https://github.com/gcash/bchd/blob/master/bchrpc/documentation/client_usage.md#why-are-transaction-ids-backwards

Also the proto file which defines the API has some comments https://github.com/gcash/bchd/blob/master/bchrpc/bchrpc.proto#L265

**Comment by selfdrivingmenee** [comment]
Thanks! This should really be part of an example, if it's quirky enough to get it's own dedicated function in the GO implementation an example for python users would really save a lot of time. Even an "hex input"->"expected output" of such conversion would be extremely useful.

**Comment by selfdrivingmenee** [comment]
Solution:

`     // Just a random tx for example purpose
       txid = "098cc42f3ff7b2665a50514bd1ed18234f3ddb8f45c4cf320e3b434386d5933e"
      // Converting to bytes
        bts=bytes.fromhex(txid)
      // Converting to bytearray as it has the reverse method
        swap_data = bytearray(bts)
        swap_data.reverse()
     // Converting back to bytes
        bts = bytes(swap_data)`

I'm positive there is more efficient method, I'm posting this here in the hope it may help some other human facing the same problem :-)
