### ISSUE TITLE
BCHD connects to the same peer multiple times, getting itself banned

### ISSUE THREAD

**Issue by gandrewstone** [gcash/bchd#448]
This is happening to on an experimental network so there just aren't 4 nodes.  The seeder always returns the same node.  We can work around by whitelisting, but could this get you banned on mainnet with some rare probability?

stone@xanadu:/fast/bitcoin/workspace/bchd$ ./bchctl --nextchain getpeerinfo
[
  {
    "id": 1,
    "addr": "159.203.179.109:7228",
    "addrlocal": "192.168.1.100:54618",
    "services": "00002165",
    "servicesStr": "SFNodeNetwork|SFNodeBloom|SFNodeXthin|SFNodeBitcoinCash|SFNodeGraphene|0x800",
    "relaytxes": true,
    "lastsend": 1615403809,
    "lastrecv": 1615403809,
    "bytessent": 1179,
    "bytesrecv": 1151,
    "conntime": 1615403808,
    "timeoffset": 0,
    "pingtime": 0,
    "version": 80003,
    "subver": "/BCH Unlimited:1.9.0.1(EB1024; AD12; 64bit)/",
    "inbound": false,
    "startingheight": 7255,
    "currentheight": 7255,
    "banscore": 0,
    "whitelisted": false,
    "feefilter": 0,
    "syncnode": true
  },
  {
    "id": 2,
    "addr": "159.203.179.109:7228",
    "addrlocal": "192.168.1.100:54616",
    "services": "00002165",
    "servicesStr": "SFNodeNetwork|SFNodeBloom|SFNodeXthin|SFNodeBitcoinCash|SFNodeGraphene|0x800",
    "relaytxes": true,
    "lastsend": 1615403809,
    "lastrecv": 1615403809,
    "bytessent": 350,
    "bytesrecv": 1151,
    "conntime": 1615403808,
    "timeoffset": 0,
    "pingtime": 0,
    "version": 80003,
    "subver": "/BCH Unlimited:1.9.0.1(EB1024; AD12; 64bit)/",
    "inbound": false,
    "startingheight": 7255,
    "currentheight": 7255,
    "banscore": 0,
    "whitelisted": false,
    "feefilter": 0,
    "syncnode": false
  },
  {
    "id": 3,
    "addr": "159.203.179.109:7228",
    "addrlocal": "192.168.1.100:54620",
    "services": "00002165",
    "servicesStr": "SFNodeNetwork|SFNodeBloom|SFNodeXthin|SFNodeBitcoinCash|SFNodeGraphene|0x800",
    "relaytxes": true,
    "lastsend": 1615403809,
    "lastrecv": 1615403809,
    "bytessent": 350,
    "bytesrecv": 1151,
    "conntime": 1615403808,
    "timeoffset": 0,
    "pingtime": 0,
    "version": 80003,
    "subver": "/BCH Unlimited:1.9.0.1(EB1024; AD12; 64bit)/",
    "inbound": false,
    "startingheight": 7255,
    "currentheight": 7255,
    "banscore": 0,
    "whitelisted": false,
    "feefilter": 0,
    "syncnode": false
  },
  {
    "id": 4,
    "addr": "159.203.179.109:7228",
    "addrlocal": "192.168.1.100:54622",
    "services": "00002165",
    "servicesStr": "SFNodeNetwork|SFNodeBloom|SFNodeXthin|SFNodeBitcoinCash|SFNodeGraphene|0x800",
    "relaytxes": true,
    "lastsend": 1615403809,
    "lastrecv": 1615403809,
    "bytessent": 350,
    "bytesrecv": 1151,
    "conntime": 1615403808,
    "timeoffset": 0,
    "pingtime": 0,
    "version": 80003,
    "subver": "/BCH Unlimited:1.9.0.1(EB1024; AD12; 64bit)/",
    "inbound": false,
    "startingheight": 7255,
    "currentheight": 7255,
    "banscore": 0,
    "whitelisted": false,
    "feefilter": 0,
    "syncnode": false
  }
]

**Comment by jcramer** [comment]
Note: There is a stale PR in progress: https://github.com/gcash/bchd/pull/296

**Comment by zquestz** [comment]
This has been fixed and will go out with the next release.
