### ISSUE TITLE
Find a way to simplify use or instantiation of KeyDB in SignTxOutput

### ISSUE THREAD

**Issue by romainPellerin** [gcash/bchd#45]
I tried to switch from btcd imports to bchd ones, unfortunately this code I had does not compile anymore:
```
lookupKey := func(a btcutil.Address) (*bchec.PrivateKey, bool, error) {
    return priv, true, nil
}
sigScript, err := txscript.SignTxOutput(&chaincfg.MainNetParams,
		redeemTx, 0, utxoSourceAmount, originTx.TxOut[0].PkScript, txscript.SigHashAll,
		txscript.KeyClosure(lookupKey), nil, nil)
```

I updated to the new way of doing so using Closures but this code does not compile as well:
```
func ... { 
//...
sigScript, err := txscript.SignTxOutput(&chaincfg.MainNetParams,
		redeemTx, 0, utxoSourceAmount, originTx.TxOut[0].PkScript, txscript.SigHashAll,
		mkGetKey(map[string]addressToKey{
			sourceAddress.EncodeAddress(): {priv, true},
		}), nil, nil)
//...
}

func mkGetKey(keys map[string]addressToKey) txscript.KeyDB {
	if keys == nil {
		return txscript.KeyClosure(func(addr btcutil.Address) (*bchec.PrivateKey,
			bool, error) {
			return nil, false, nil
		})
	}
	return txscript.KeyClosure(func(addr btcutil.Address) (*bchec.PrivateKey,
		bool, error) {
		a2k, ok := keys[addr.EncodeAddress()]
		if !ok {
			return nil, false, nil
		}
		return a2k.key, a2k.compressed, nil
	})
}
```

I am surely missing something here, but I think it's a pretty complicated way to pass the private key for signature, even if it was originally created as an helper and for a better security.

We could introduce an additional simpler method to do so.

Just my 2 cts. What do you think?

**Comment by cpacia** [comment]
@romainPellerin take a look at `RawTxInSignature`. It might be more of what you're looking for.

**Comment by romainPellerin** [comment]
@cpacia I will thanks

**Comment by zquestz** [comment]
Going to close this since `RawTxInSignature` should do the job. Feel free to reopen if you still need this looked at.
