### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by Rohithzr** [gcash/bchd#465]
I am trying to implement webhook based wallet management via bchd, I want something like a walletnotify / blocknotify of the bitcoind implementation.

I am trying to find the right docs with no luck, can someone point me to the right direction?

**Comment by jcramer** [comment]
BCHD has a built in gRPC server with transaction and block notification streams available.  You can build your own client from the bchrpc.proto file: https://github.com/gcash/bchd/blob/master/bchrpc/README.md

Or use of of these existing existing client library:
- https://github.com/simpleledgerinc/grpc-bchrpc-node
- https://github.com/simpleledgerinc/grpc-bchrpc-web
- https://pub.dev/packages/grpc_bchrpc
- https://pub.dev/packages/grpc_bchrpc_web

**Comment by zquestz** [comment]
Looks like James provided the info. If you need more assistance you can reopen the issue.
