### ISSUE TITLE
cryptolayer.net seed constantly failing

### ISSUE THREAD

**Issue by tyler-smith** [gcash/bchd#48]
Every boot I see that seeder.cryptolayer.net is failing:

```
2018-10-07 14:12:31.503 [INF] CMGR: DNS discovery failed on seed seeder.criptolayer.net: lookup seeder.criptolayer.net on 127.0.0.53:53: server misbehaving
```

We should probably remove this seed, and if we think we need more seeds we should consider a bchd.cash seed.

**Comment by zquestz** [comment]
Works for me:

`2018-10-08 17:29:05.499 [INF] CMGR: 100 addresses found from DNS seed seeder.criptolayer.net`

**Comment by tyler-smith** [comment]
Yeah it's been working for me this morning. If it's up periodically it's still better than not having it so I'll close this issue.
