### ISSUE TITLE
Compile to WebAssembly

### ISSUE THREAD

**Issue by Jonas-Metzger** [gcash/bchd#481]
I'd like to compile bchd to webassembly. More specifically, I'd like to get a .wasm file that you can supply a new block and a (already validated) block history to, and let it verify that the new block is valid.

Is this possible? If yes, what do I have to do?

I cloned the repo and executed

`GOOS=js GOARCH=wasm go build -o main.wasm` 

Hoping that maybe the whole repo would just compile. However, no main.wasm file is produced. Instead, I get the following output:

```
# github.com/gcash/bchd/limits
limits/limits_unix.go:22:13: undefined: syscall.Rlimit
limits/limits_unix.go:24:9: undefined: syscall.Getrlimit
limits/limits_unix.go:24:27: undefined: syscall.RLIMIT_NOFILE
limits/limits_unix.go:41:8: undefined: syscall.Setrlimit
limits/limits_unix.go:41:26: undefined: syscall.RLIMIT_NOFILE
limits/limits_unix.go:45:9: undefined: syscall.Setrlimit
limits/limits_unix.go:45:27: undefined: syscall.RLIMIT_NOFILE
# github.com/btcsuite/goleveldb/leveldb/storage
../../go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:107:16: undefined: newFileLock
../../go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:192:3: undefined: rename
../../go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:267:12: undefined: rename
../../go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:272:12: undefined: syncDir
../../go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:555:9: undefined: rename
../../go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:591:13: undefined: syncDir
```
I have the go version go1.16.5 linux/amd64.

As you can tell, I have no idea what I'm doing or how any of this works. Any help/info would be greatly appreciated!

**Comment by zquestz** [comment]
Yeah, wasm is not supported at this time. The errors you are seeing are architecture dependent files. Someone would need update the limits code and file storage to support wasm before it will build.

**Comment by Jonas-Metzger** [comment]
Thanks a lot for the info! How hard/interesting to the devs is it to do that, at least for the part of the code that validates blocks?

The application I have in mind is a bridge to Ethereum via a smart contract keeping track of and validating the BCH blockchain through [Truebit ](https://truebit.io/) (which requires WASM).

**Comment by zquestz** [comment]
Not sure, the changes in bchd are actually quite simple, just need to add stubs for the limits methods for WASM compilation. However, we have dependency on goleveldb, and I am sure how hard it will be to update the file storage code.
