### ISSUE TITLE
Prune mode not working 

### ISSUE THREAD

**Issue by aconsuegra2014** [gcash/bchd#484]
Hello I'm running a bchd server in prune mode and it is not working as expected .

./bchd --version
bchd version 0.18.1

I set up the following options
prune=1

prunedepth=300

fastsync=1

Currently the space in hard disk is 22G and growing 

du -h .
3.8G	./blocks_ffldb/metadata
22G	./blocks_ffldb
22G	.

It is a bug or my settings are wrong

**Comment by Ekliptor** [comment]
That seems ok. The UTXO is > 20 GB.
For comparison, my BCHD including SLP index uses over 240 GB of space.

**Comment by aconsuegra2014** [comment]
There is a way to know the maximum size on disk that can grown with prunedepth=300

**Comment by Ekliptor** [comment]
You still need to keep:
- the 300 latest blocks
- the UTXO which is > 20 GB

I'm not familiar with the BCHD storage format, but you can't expect (much) less than tat on disk.
