### ISSUE TITLE
Public BCHD instances are missing CORS headers when gRPC-web is used.

### ISSUE THREAD

**Issue by artemii235** [gcash/bchd#489]
I have added BCHD API gRPC-web support for SLP transactions validation as a part of the integration to the AtomicDEX https://github.com/KomodoPlatform/atomicDEX-API/issues/701. We also have an ongoing web browsers support implementation (WASM) so I tried requesting BCHD instances from the Firefox browser but got CORS Missing Allow Origin errors. Is it possible to enable CORS headers on all BCHD public instances?

![image](https://user-images.githubusercontent.com/15745003/137115218-cae74ea3-96f7-44a7-a9c1-db88d50811b0.png)

PS I'm unsure if this is a correct place to post such an issue. Please forward me to an appropriate communication channel if required.

**Comment by Ekliptor** [comment]
Is there any error message in the response?

In case its a parameter error, using the REST API proxy might help: https://bchd.fountainhead.cash/swagger.html
Its just a wrapper for the gRPC/gRPC-web functions. So if it still fails we need a BCHD log to dig deeper.
In that case can you please post reproducable code of your request that fails?

**Comment by artemii235** [comment]
@Ekliptor We've asked for help in BCHD operators Telegram and discovered that the `x-grpc-web` header was required in the request. `OPTIONS` started to work as expected for us, thanks!
