### ISSUE TITLE
Consider adding this project to the Awesome Go list

### ISSUE THREAD

**Issue by vucefalas** [gcash/bchd#502]
I believe it would be useful and would increase its visibility if this project was added to the [Awesome Go list](https://github.com/avelino/awesome-go).

[These are the criteria](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md) that a project must fit in order to be accepted into that list:

- have an **open source license**, [see list of allowed licenses](https://opensource.org/licenses/alphabetical);
- function as documented and expected;
- be generally useful to the wider community of Go programmers;
- be actively maintained with:
  - regular, recent commits;
  - or, for finished projects, issues and pull requests are responded to generally within 2 weeks;
- be stable or progressing toward stable;
- be thoroughly documented (README, pkg.go.dev doc comments, etc.) in the english language, so everyone is able to understand the project's intention and how it works. All public functions and types should have a Go style documentation header;
- if the library/program is testable, then coverage should be >= 80% for non-data-related packages and >=90% for data related packages. (**Note**: the tests will be reviewed too. We will check your coverage manually if your package's coverage is just a benchmark results);
- have at least one official version-numbered release that allows go.mod files to list the file by version number, of the form vX.X.X.

**Comment by zquestz** [comment]
Thanks for the heads up!
