### ISSUE TITLE
RPC GetAddressUnspentOutputsResponse missing index

### ISSUE THREAD

**Issue by mariusk** [gcash/bchd#514]
According to docs for `GetAddressUnspentOutputs` which returns https://www.grpc.cash/docs/bchrpc/#pb.UnspentOutput, `output` points to `outpoint` which returns a `Transaction.Input.Output`, which  again is supposed to return a `hash` **and** an `index` (https://www.grpc.cash/docs/bchrpc/#pb.Transaction.Input.Outpoint). The actual reponse returns a hash, but no index. The index is needed to uniquely match a coin to it's output in a transaction. Considering the docs specifies `index` should be returned (and it is actually needed to track a coin), is this a bug? Any other/better way to figure out which outputs in a transaction for a given address is actually unspent?

**Comment by zquestz** [comment]
I think this might just be a result of default values not being output. Any chance it is index 0?

What is the actual tx? I would like to test some grpc curl commands to replicate the issue.

**Comment by mariusk** [comment]
Here's the transaction, I'm specifically trying to track the 80307 amount: 

https://www.blockchain.com/bch/tx/3f51ce835ea5cc8d24b44aa68dd9719a1f1feb2d46d2c2f93c9604f60a62e1c4

The index in the out list of that transaction is zero yes.

**Comment by mariusk** [comment]
I think I was able to confirm your suspicion about `index` not showing if it is `0`. Here's another address I found where the unspent outputs was not at index zero and then the index does get included:
```
debug: { args: { showunspent: 'qptlgd5zwc0lk7yg8azfq2hwp36urq6tysxk5yecxf' } }
(node:97714) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)
{
  outputs: [
    {
      outpoint: {
        hash: <Buffer 8a 5b 61 10 ce 6e e0 4e 1c 95 4d 6b 7e 85 98 46 dd 6e e3 b8 2c 52 ce ba aa 4b 03 d1 a6 08 87 74>,
        index: 1
      },
      pubkeyScript: <Buffer 76 a9 14 57 f4 36 82 76 1f fb 78 88 3f 44 90 2a ee 0c 75 c1 83 4b 24 88 ac>,
      value: Long { low: 4992935, high: 0, unsigned: false },
      blockHeight: 760333
    },
    {
      outpoint: {
        hash: <Buffer dd 45 b8 75 fb 16 9c 36 da 82 0b f7 88 60 3d 24 3e 88 93 8b 4a 36 6f e3 be 58 cf 5f a6 45 ca 67>,
        index: 1
      },
      pubkeyScript: <Buffer 76 a9 14 57 f4 36 82 76 1f fb 78 88 3f 44 90 2a ee 0c 75 c1 83 4b 24 88 ac>,
      value: Long { low: 11788845, high: 0, unsigned: false },
      blockHeight: 760333
    }
  ]
}
```
A bit confusing I have to say, but easy to support with knowledge about it. Thanks, and closing issue.
