### ISSUE TITLE
Set up responsible disclosure process

### ISSUE THREAD

**Issue by cpacia** [gcash/bchd#54]
One of the issues identified by both Cory Fields and Awemany is it was difficult to find a PGP key and email to submit critical bugs to. 

We should come up with a way to make it sure it's easy for people to figure out how to send us confidential emails.

**Comment by zquestz** [comment]
Feel free to include my info:

```
pub  4096R/00228DDD 2013-07-14 quest <quest@mac.com>
	 Fingerprint=B6DE 3514 E07E 30BB 5F40  8D74 E49B 7E00 0022 8DDD 
```
