### ISSUE TITLE
go get is a deprecated installation method

### ISSUE THREAD

**Issue by checksum0** [gcash/bchd#555]
The README.md documentation mentions that you can build from source bchd using the `go get` command while the `go.mod` file specify a minimum go version of v1.23.4.

`go get` without a local go.mod file is a deprecated after go v1.17 in favor of `go install github.com/gcash/bchd@latest`. Note that install command disregard versions with a pre-release tag according to the semantic versioning 2.0.0, thus try to install v0.19.0 which is currently out-of-consensus. I would suggest forcing a version in the documentation until a version that is in-consensus has been properly released.

**Comment by zquestz** [comment]
Fixed.
