### ISSUE TITLE
Make stall ticker detect very slow syncPeer

### ISSUE THREAD

**Issue by emergent-reasons** [gcash/bchd#98]
Based on the conversation [here](https://github.com/gcash/bchd/pull/96#discussion_r228716624), it is possible to have a syncPeer that stays connected but is very slow. It's probably hard to know who is the cause of slowness, but if we can detect the problem and drop the current syncPeer when transfer is very slow, it should help on average.

**Comment by zquestz** [comment]
I am currently working on this. =)
